/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DesktopSGU.java
 *
 * Created on 01/07/2011, 14:38:32
 */
package main;

import java.awt.Dimension;
import view.escola.BibliotecaRelatarVIEW;
import view.escola.ClasseCadastroVIEW;
import view.escola.BibliotecaVIEW;
import view.escola.AlunoRelatorioIndividualVIEW;
import view.escola.PlanejamentoRotinaSemanalVIEW;
import view.escola.AlunoCadastroVIEW;
import view.escola.BibliotecaConsultaDIALOG;
import view.escola.ListaTelefonicaVIEW;
import sobre.Sobre;
import java.awt.Frame;
import java.awt.Toolkit;
import lib.java.Senha;
import relatorios.RelatorioIndividualdoAlunoRL;
import view.comercio.VendasVIEW;
//import view.auto.ClienteCadastroVIEW;
import view.escola.AlunoConsultaDIALOG;
import view.escola.BibliotecaConsultaTomboDIALOG;
import view.escola.InformaticaCadastrarEquipamentos;
import view.escola.PessoaAniversarioVIEW;
import view.escola.PessoaNasMultVIEW;

/**
 *
 * @author Douglas Estanislau Pereira
 */
public class DesktopSGU extends javax.swing.JFrame {

    /** Creates new form DesktopSGU */
    public DesktopSGU() {
        initComponents();
        Tela();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneSGUVIEW = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSGU = new javax.swing.JMenu();
        jMenuItemSGSESair = new javax.swing.JMenuItem();
        jMenuEscola = new javax.swing.JMenu();
        jMenuAEE = new javax.swing.JMenu();
        jMenuAEERelatorio = new javax.swing.JMenu();
        jMenuItemAEERelatorioAluno = new javax.swing.JMenuItem();
        jMenuAlmoxerifado = new javax.swing.JMenu();
        jMenuBiblioteca = new javax.swing.JMenu();
        jMenuItemCadastrarAcervo = new javax.swing.JMenuItem();
        jMenuItemConsultarAcervo = new javax.swing.JMenuItem();
        jMenuItemConsultarTombo = new javax.swing.JMenuItem();
        jMenuItemRelatarEntradaSaida = new javax.swing.JMenuItem();
        jMenuCoordenacao = new javax.swing.JMenu();
        jMenuDiretoria = new javax.swing.JMenu();
        jMenuDiretoriaCadastrar = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuFonoaudiologo = new javax.swing.JMenu();
        jMenuFonoaudiologoRelatorio = new javax.swing.JMenu();
        jMenuItemFonoaudiologoRelatorioIndividualAluno = new javax.swing.JMenuItem();
        jMenuInformatica = new javax.swing.JMenu();
        jMenuInformaticaCadastro = new javax.swing.JMenu();
        jMenuItemInformaticaCadastroEquipamento = new javax.swing.JMenuItem();
        jMenuProfessores = new javax.swing.JMenu();
        jMenuProfessorRelatorios = new javax.swing.JMenu();
        jMenuItemProfessorRelatorioAluno = new javax.swing.JMenuItem();
        jMenuItemProfessoresRelatorioClasse = new javax.swing.JMenuItem();
        jMenuItemProfessoresEncamiamento = new javax.swing.JMenuItem();
        jMenuItemProfessorPRS = new javax.swing.JMenuItem();
        jMenuItemConsultarListaTelefonica = new javax.swing.JMenuItem();
        jMenuPsicologo = new javax.swing.JMenu();
        jMenuPsicologaRelatorio = new javax.swing.JMenu();
        jMenuItemPsicologoRelatorioRelatorioIndividualdoAluno = new javax.swing.JMenuItem();
        jMenuSecretaria = new javax.swing.JMenu();
        jMenuSecretariaCadastrar = new javax.swing.JMenu();
        jMenuItemCadastrarAluno = new javax.swing.JMenuItem();
        jMenuItemCadastrarClasse = new javax.swing.JMenuItem();
        jMenuItemCadastrarAlunoClasse = new javax.swing.JMenuItem();
        jMenuItemLoginSenha = new javax.swing.JMenuItem();
        jMenuSecretariaConsultar = new javax.swing.JMenu();
        jMenuItemSecretariaConsultarListaTelefonica = new javax.swing.JMenuItem();
        jMenuItemAlunoConsulta = new javax.swing.JMenuItem();
        jMenuSecretariaImprimir = new javax.swing.JMenu();
        jMenuItemSecretariaImprimirRIAluno = new javax.swing.JMenuItem();
        jMenuListar = new javax.swing.JMenu();
        jMenuItemListarAniversario = new javax.swing.JMenuItem();
        jMenuItemPessoaNM = new javax.swing.JMenuItem();
        jMenuAuto = new javax.swing.JMenu();
        jMenuAutoCadastro = new javax.swing.JMenu();
        jMenuItemAutoCadastroClientes = new javax.swing.JMenuItem();
        jMenuItemAutoCadastroFuncionarios = new javax.swing.JMenuItem();
        jMenuItemAutoCadastroProdutos = new javax.swing.JMenuItem();
        jMenuItemAutoCadastroCarros = new javax.swing.JMenuItem();
        jMenuComercio = new javax.swing.JMenu();
        jMenuComercioCadastrar = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemComercioRealizarVendas = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemAjudaSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);
        getContentPane().add(jDesktopPaneSGUVIEW);
        jDesktopPaneSGUVIEW.setBounds(0, 0, 1366, 800);

        jMenuSGU.setText("SGU");

        jMenuItemSGSESair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemSGSESair.setText("Sair");
        jMenuItemSGSESair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSGSESairActionPerformed(evt);
            }
        });
        jMenuSGU.add(jMenuItemSGSESair);

        jMenuBar1.add(jMenuSGU);

        jMenuEscola.setText("Escola");

        jMenuAEE.setText("AEE");

        jMenuAEERelatorio.setText("Relatório");

        jMenuItemAEERelatorioAluno.setText("Aluno...");
        jMenuItemAEERelatorioAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAEERelatorioAlunoActionPerformed(evt);
            }
        });
        jMenuAEERelatorio.add(jMenuItemAEERelatorioAluno);

        jMenuAEE.add(jMenuAEERelatorio);

        jMenuEscola.add(jMenuAEE);

        jMenuAlmoxerifado.setText("Almoxerifado");
        jMenuEscola.add(jMenuAlmoxerifado);

        jMenuBiblioteca.setText("Biblioteca");

        jMenuItemCadastrarAcervo.setText("Cadastrar Acervo...");
        jMenuItemCadastrarAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarAcervoActionPerformed(evt);
            }
        });
        jMenuBiblioteca.add(jMenuItemCadastrarAcervo);

        jMenuItemConsultarAcervo.setText("Consultar Acervo...");
        jMenuItemConsultarAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarAcervoActionPerformed(evt);
            }
        });
        jMenuBiblioteca.add(jMenuItemConsultarAcervo);

        jMenuItemConsultarTombo.setText("Consultar Tombo...");
        jMenuItemConsultarTombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarTomboActionPerformed(evt);
            }
        });
        jMenuBiblioteca.add(jMenuItemConsultarTombo);

        jMenuItemRelatarEntradaSaida.setText("Relatar Entrada/Saída...");
        jMenuItemRelatarEntradaSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatarEntradaSaidaActionPerformed(evt);
            }
        });
        jMenuBiblioteca.add(jMenuItemRelatarEntradaSaida);

        jMenuEscola.add(jMenuBiblioteca);

        jMenuCoordenacao.setText("Coodenação");
        jMenuEscola.add(jMenuCoordenacao);

        jMenuDiretoria.setText("Diretoria");

        jMenuDiretoriaCadastrar.setText("Cadastrar");

        jMenuItem1.setText("Ocorrências...");
        jMenuDiretoriaCadastrar.add(jMenuItem1);

        jMenuDiretoria.add(jMenuDiretoriaCadastrar);

        jMenuEscola.add(jMenuDiretoria);

        jMenuFonoaudiologo.setText("Fonoaudiólogo");

        jMenuFonoaudiologoRelatorio.setText("Relatório");

        jMenuItemFonoaudiologoRelatorioIndividualAluno.setText("Aluno...");
        jMenuItemFonoaudiologoRelatorioIndividualAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFonoaudiologoRelatorioIndividualAlunoActionPerformed(evt);
            }
        });
        jMenuFonoaudiologoRelatorio.add(jMenuItemFonoaudiologoRelatorioIndividualAluno);

        jMenuFonoaudiologo.add(jMenuFonoaudiologoRelatorio);

        jMenuEscola.add(jMenuFonoaudiologo);

        jMenuInformatica.setText("Informática");

        jMenuInformaticaCadastro.setText("Cadastrar");

        jMenuItemInformaticaCadastroEquipamento.setText("Equipamentos...");
        jMenuItemInformaticaCadastroEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInformaticaCadastroEquipamentoActionPerformed(evt);
            }
        });
        jMenuInformaticaCadastro.add(jMenuItemInformaticaCadastroEquipamento);

        jMenuInformatica.add(jMenuInformaticaCadastro);

        jMenuEscola.add(jMenuInformatica);

        jMenuProfessores.setText("Professores");

        jMenuProfessorRelatorios.setText("Relatório");

        jMenuItemProfessorRelatorioAluno.setText("Aluno...");
        jMenuItemProfessorRelatorioAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProfessorRelatorioAlunoActionPerformed(evt);
            }
        });
        jMenuProfessorRelatorios.add(jMenuItemProfessorRelatorioAluno);

        jMenuItemProfessoresRelatorioClasse.setText("Classe...");
        jMenuProfessorRelatorios.add(jMenuItemProfessoresRelatorioClasse);

        jMenuProfessores.add(jMenuProfessorRelatorios);

        jMenuItemProfessoresEncamiamento.setText("Encamiamento...");
        jMenuProfessores.add(jMenuItemProfessoresEncamiamento);

        jMenuItemProfessorPRS.setText("Planejamento da Rotina Semanal...");
        jMenuItemProfessorPRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProfessorPRSActionPerformed(evt);
            }
        });
        jMenuProfessores.add(jMenuItemProfessorPRS);

        jMenuItemConsultarListaTelefonica.setText("Consultar Lista Telefonica...");
        jMenuItemConsultarListaTelefonica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarListaTelefonicaActionPerformed(evt);
            }
        });
        jMenuProfessores.add(jMenuItemConsultarListaTelefonica);

        jMenuEscola.add(jMenuProfessores);

        jMenuPsicologo.setText("Psicólogo");

        jMenuPsicologaRelatorio.setText("Relatório");

        jMenuItemPsicologoRelatorioRelatorioIndividualdoAluno.setText("Aluno...");
        jMenuItemPsicologoRelatorioRelatorioIndividualdoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPsicologoRelatorioRelatorioIndividualdoAlunoActionPerformed(evt);
            }
        });
        jMenuPsicologaRelatorio.add(jMenuItemPsicologoRelatorioRelatorioIndividualdoAluno);

        jMenuPsicologo.add(jMenuPsicologaRelatorio);

        jMenuEscola.add(jMenuPsicologo);

        jMenuSecretaria.setText("Secretaria");

        jMenuSecretariaCadastrar.setText("Cadastrar");

        jMenuItemCadastrarAluno.setText("Alunos/Docentes/Funcionários...");
        jMenuItemCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarAlunoActionPerformed(evt);
            }
        });
        jMenuSecretariaCadastrar.add(jMenuItemCadastrarAluno);

        jMenuItemCadastrarClasse.setText("Classe...");
        jMenuItemCadastrarClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarClasseActionPerformed(evt);
            }
        });
        jMenuSecretariaCadastrar.add(jMenuItemCadastrarClasse);

        jMenuItemCadastrarAlunoClasse.setText("Alunos a Classe...");
        jMenuSecretariaCadastrar.add(jMenuItemCadastrarAlunoClasse);

        jMenuItemLoginSenha.setText("Login/Senha...");
        jMenuItemLoginSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginSenhaActionPerformed(evt);
            }
        });
        jMenuSecretariaCadastrar.add(jMenuItemLoginSenha);

        jMenuSecretaria.add(jMenuSecretariaCadastrar);

        jMenuSecretariaConsultar.setText("Consultar");

        jMenuItemSecretariaConsultarListaTelefonica.setText("Lista Telefônica...");
        jMenuItemSecretariaConsultarListaTelefonica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSecretariaConsultarListaTelefonicaActionPerformed(evt);
            }
        });
        jMenuSecretariaConsultar.add(jMenuItemSecretariaConsultarListaTelefonica);

        jMenuItemAlunoConsulta.setText("Aluno...");
        jMenuItemAlunoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlunoConsultaActionPerformed(evt);
            }
        });
        jMenuSecretariaConsultar.add(jMenuItemAlunoConsulta);

        jMenuSecretaria.add(jMenuSecretariaConsultar);

        jMenuSecretariaImprimir.setText("Imprimir");

        jMenuItemSecretariaImprimirRIAluno.setText("Relatório Individual do Aluno...");
        jMenuItemSecretariaImprimirRIAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSecretariaImprimirRIAlunoActionPerformed(evt);
            }
        });
        jMenuSecretariaImprimir.add(jMenuItemSecretariaImprimirRIAluno);

        jMenuSecretaria.add(jMenuSecretariaImprimir);

        jMenuListar.setText("Listar");

        jMenuItemListarAniversario.setText("Aniversários...");
        jMenuItemListarAniversario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarAniversarioActionPerformed(evt);
            }
        });
        jMenuListar.add(jMenuItemListarAniversario);

        jMenuItemPessoaNM.setText("Nascimento Múltiplos...");
        jMenuItemPessoaNM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPessoaNMActionPerformed(evt);
            }
        });
        jMenuListar.add(jMenuItemPessoaNM);

        jMenuSecretaria.add(jMenuListar);

        jMenuEscola.add(jMenuSecretaria);

        jMenuBar1.add(jMenuEscola);

        jMenuAuto.setText("Auto");

        jMenuAutoCadastro.setText("Cadastrar");

        jMenuItemAutoCadastroClientes.setText("Clientes...");
        jMenuItemAutoCadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAutoCadastroClientesActionPerformed(evt);
            }
        });
        jMenuAutoCadastro.add(jMenuItemAutoCadastroClientes);

        jMenuItemAutoCadastroFuncionarios.setText("Funcionários...");
        jMenuAutoCadastro.add(jMenuItemAutoCadastroFuncionarios);

        jMenuItemAutoCadastroProdutos.setText("Produtos/Serviços...");
        jMenuAutoCadastro.add(jMenuItemAutoCadastroProdutos);

        jMenuItemAutoCadastroCarros.setText("Carros...");
        jMenuAutoCadastro.add(jMenuItemAutoCadastroCarros);

        jMenuAuto.add(jMenuAutoCadastro);

        jMenuBar1.add(jMenuAuto);

        jMenuComercio.setText("Comercio");

        jMenuComercioCadastrar.setText("Cadastrar");

        jMenuItem2.setText("Clientes");
        jMenuComercioCadastrar.add(jMenuItem2);

        jMenuItem3.setText("Funcionários");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuComercioCadastrar.add(jMenuItem3);

        jMenuItem5.setText("Produtos");
        jMenuComercioCadastrar.add(jMenuItem5);

        jMenuComercio.add(jMenuComercioCadastrar);

        jMenu1.setText("Realizar");

        jMenuItemComercioRealizarVendas.setText("Vendas");
        jMenuItemComercioRealizarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemComercioRealizarVendasActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemComercioRealizarVendas);

        jMenuComercio.add(jMenu1);

        jMenuBar1.add(jMenuComercio);

        jMenuAjuda.setText("Ajuda");

        jMenuItemAjudaSobre.setText("Sobre");
        jMenuItemAjudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAjudaSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemAjudaSobre);

        jMenuBar1.add(jMenuAjuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSGSESairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSGSESairActionPerformed
        Sair();
    }//GEN-LAST:event_jMenuItemSGSESairActionPerformed

    private void jMenuItemCadastrarAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarAcervoActionPerformed
        CadastrarAcervoBiblioteca();
    }//GEN-LAST:event_jMenuItemCadastrarAcervoActionPerformed

    private void jMenuItemAjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAjudaSobreActionPerformed
        Sobre();
    }//GEN-LAST:event_jMenuItemAjudaSobreActionPerformed

    private void jMenuItemConsultarAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarAcervoActionPerformed
        ConsultarAcervoBiblioteca();
    }//GEN-LAST:event_jMenuItemConsultarAcervoActionPerformed

    private void jMenuItemRelatarEntradaSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatarEntradaSaidaActionPerformed
        RelatarEntradaSaida();
    }//GEN-LAST:event_jMenuItemRelatarEntradaSaidaActionPerformed

    private void jMenuItemCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarAlunoActionPerformed
        CadastrarAluno();
    }//GEN-LAST:event_jMenuItemCadastrarAlunoActionPerformed

    private void jMenuItemProfessorRelatorioAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProfessorRelatorioAlunoActionPerformed
        ProfessorRelatorioAluno();
    }//GEN-LAST:event_jMenuItemProfessorRelatorioAlunoActionPerformed

    private void jMenuItemCadastrarClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarClasseActionPerformed
        CadastrarClasse();
    }//GEN-LAST:event_jMenuItemCadastrarClasseActionPerformed

    private void jMenuItemSecretariaConsultarListaTelefonicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSecretariaConsultarListaTelefonicaActionPerformed
        ConsultarListaTelefonica();
    }//GEN-LAST:event_jMenuItemSecretariaConsultarListaTelefonicaActionPerformed

    private void jMenuItemSecretariaImprimirRIAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSecretariaImprimirRIAlunoActionPerformed
        RelatorioIndividualAluno();
    }//GEN-LAST:event_jMenuItemSecretariaImprimirRIAlunoActionPerformed

    private void jMenuItemProfessorPRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProfessorPRSActionPerformed
        ProfessorPRS();
    }//GEN-LAST:event_jMenuItemProfessorPRSActionPerformed

    private void jMenuItemAutoCadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAutoCadastroClientesActionPerformed
        // TODO add your handling code here:
        CadastrarCliente();
    }//GEN-LAST:event_jMenuItemAutoCadastroClientesActionPerformed

    private void jMenuItemConsultarListaTelefonicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarListaTelefonicaActionPerformed
        // TODO add your handling code here:
        ConsultarListaTelefonica();
    }//GEN-LAST:event_jMenuItemConsultarListaTelefonicaActionPerformed

    private void jMenuItemConsultarTomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarTomboActionPerformed
        // TODO add your handling code here:
        ConsultarTomboEmpresa();
    }//GEN-LAST:event_jMenuItemConsultarTomboActionPerformed

    private void jMenuItemAlunoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlunoConsultaActionPerformed
        // TODO add your handling code here:
        AlunoConsultaDIALOG jDialog = new AlunoConsultaDIALOG(null, true);
        jDialog.setModal(true);
        jDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemAlunoConsultaActionPerformed

    private void jMenuItemLoginSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginSenhaActionPerformed
        // TODO add your handling code here:
        Senha senha = new Senha(null, true);
        senha.setModal(true);
        senha.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemLoginSenhaActionPerformed

    private void jMenuItemPsicologoRelatorioRelatorioIndividualdoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPsicologoRelatorioRelatorioIndividualdoAlunoActionPerformed
        // TODO add your handling code here:
        AlunoRelatorioIndividualVIEW aluno = new AlunoRelatorioIndividualVIEW();
        jDesktopPaneSGUVIEW.add(aluno);
        aluno.setVisible(true);
    }//GEN-LAST:event_jMenuItemPsicologoRelatorioRelatorioIndividualdoAlunoActionPerformed

    private void jMenuItemAEERelatorioAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAEERelatorioAlunoActionPerformed
        // TODO add your handling code here:
        AlunoRelatorioIndividualVIEW aluno = new AlunoRelatorioIndividualVIEW();
        jDesktopPaneSGUVIEW.add(aluno);
        aluno.setVisible(true);
    }//GEN-LAST:event_jMenuItemAEERelatorioAlunoActionPerformed

    private void jMenuItemFonoaudiologoRelatorioIndividualAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFonoaudiologoRelatorioIndividualAlunoActionPerformed
        // TODO add your handling code here:
        AlunoRelatorioIndividualVIEW aluno = new AlunoRelatorioIndividualVIEW();
        jDesktopPaneSGUVIEW.add(aluno);
        aluno.setVisible(true);
    }//GEN-LAST:event_jMenuItemFonoaudiologoRelatorioIndividualAlunoActionPerformed

    private void jMenuItemInformaticaCadastroEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInformaticaCadastroEquipamentoActionPerformed
        // TODO add your handling code here:
        InformaticaCadastrarEquipamentos cadastro = new InformaticaCadastrarEquipamentos();
        jDesktopPaneSGUVIEW.add(cadastro);
        cadastro.setVisible(true);
    }//GEN-LAST:event_jMenuItemInformaticaCadastroEquipamentoActionPerformed

    private void jMenuItemListarAniversarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarAniversarioActionPerformed
        // TODO add your handling code here:
        PessoaAniversarioVIEW l = new PessoaAniversarioVIEW();
        jDesktopPaneSGUVIEW.add(l);
        l.setVisible(true);
    }//GEN-LAST:event_jMenuItemListarAniversarioActionPerformed

    private void jMenuItemPessoaNMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPessoaNMActionPerformed
        // TODO add your handling code here:
        PessoaNasMultVIEW nm = new PessoaNasMultVIEW();
        jDesktopPaneSGUVIEW.add(nm);
        nm.setVisible(true);
    }//GEN-LAST:event_jMenuItemPessoaNMActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItemComercioRealizarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemComercioRealizarVendasActionPerformed
        // TODO add your handling code here:
        VendasVIEW f = new VendasVIEW();
        jDesktopPaneSGUVIEW.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItemComercioRealizarVendasActionPerformed

    //#########################################################################
    // AUTO
    
    public void CadastrarCliente(){
        //ClienteCadastroVIEW f = new ClienteCadastroVIEW();
        //jDesktopPaneSGUVIEW.add(f);
        //f.setVisible(true);
    }
    //#########################################################################
    
    public void ConsultarTomboEmpresa(){
        BibliotecaConsultaTomboDIALOG  jDialog = new BibliotecaConsultaTomboDIALOG(null, true);
        jDialog.setModal(true);
        jDialog.setVisible(true);
    }
    
    public void ProfessorRelatorioAluno(){
        AlunoRelatorioIndividualVIEW aluno = new AlunoRelatorioIndividualVIEW();
        jDesktopPaneSGUVIEW.add(aluno);
        aluno.setVisible(true);
    }
    
    public void RelatorioIndividualAluno(){
        RelatorioIndividualdoAlunoRL relatorio = new RelatorioIndividualdoAlunoRL();
        jDesktopPaneSGUVIEW.add(relatorio);
        relatorio.setVisible(true);
    }
    
    public void ConsultarListaTelefonica(){
        ListaTelefonicaVIEW lista = new ListaTelefonicaVIEW();
        jDesktopPaneSGUVIEW.add(lista);
        lista.setVisible(true);
    }
    
    public void RelatarEntradaSaida(){
        BibliotecaRelatarVIEW f = new BibliotecaRelatarVIEW();
        jDesktopPaneSGUVIEW.add(f);
        f.setVisible(true);
    }
    
    public void CadastrarClasse(){
        ClasseCadastroVIEW classe = new ClasseCadastroVIEW();
        jDesktopPaneSGUVIEW.add(classe);
        classe.setVisible(true);
    }
    
    public void ProfessorPRS(){
        PlanejamentoRotinaSemanalVIEW f = new PlanejamentoRotinaSemanalVIEW();
        jDesktopPaneSGUVIEW.add(f);
        f.setVisible(true);
    }
    
    public void CadastrarAluno(){
        AlunoCadastroVIEW aluno = new AlunoCadastroVIEW();
        jDesktopPaneSGUVIEW.add(aluno);
        aluno.setVisible(true);
    }
    
    public void Tela() {
        this.setExtendedState(Frame.MAXIMIZED_BOTH);
        this.setTitle("SGU - Sistema Gerenciador UNIVERSAL");
          
        Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
        int lar = (int) tela.getWidth();
        int alt = (int) tela.getHeight();
        
        jDesktopPaneSGUVIEW.setSize(lar, alt);
    }
    
    public void Sobre(){
        Sobre f = new Sobre();
        jDesktopPaneSGUVIEW.add(f);
        f.setVisible(true);
    }

    private void Sair() {
        this.dispose();
    }

    public void CadastrarAcervoBiblioteca() {
        BibliotecaVIEW f = new BibliotecaVIEW();
        jDesktopPaneSGUVIEW.add(f);
        f.setVisible(true);
    }
    
    public void ConsultarAcervoBiblioteca() {
        BibliotecaConsultaDIALOG  jDialog = new BibliotecaConsultaDIALOG(null, true);
        jDialog.setModal(true);
        jDialog.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new DesktopSGU().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane jDesktopPaneSGUVIEW;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAEE;
    private javax.swing.JMenu jMenuAEERelatorio;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenu jMenuAlmoxerifado;
    private javax.swing.JMenu jMenuAuto;
    private javax.swing.JMenu jMenuAutoCadastro;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBiblioteca;
    private javax.swing.JMenu jMenuComercio;
    private javax.swing.JMenu jMenuComercioCadastrar;
    private javax.swing.JMenu jMenuCoordenacao;
    private javax.swing.JMenu jMenuDiretoria;
    private javax.swing.JMenu jMenuDiretoriaCadastrar;
    private javax.swing.JMenu jMenuEscola;
    private javax.swing.JMenu jMenuFonoaudiologo;
    private javax.swing.JMenu jMenuFonoaudiologoRelatorio;
    private javax.swing.JMenu jMenuInformatica;
    private javax.swing.JMenu jMenuInformaticaCadastro;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemAEERelatorioAluno;
    private javax.swing.JMenuItem jMenuItemAjudaSobre;
    private javax.swing.JMenuItem jMenuItemAlunoConsulta;
    private javax.swing.JMenuItem jMenuItemAutoCadastroCarros;
    private javax.swing.JMenuItem jMenuItemAutoCadastroClientes;
    private javax.swing.JMenuItem jMenuItemAutoCadastroFuncionarios;
    private javax.swing.JMenuItem jMenuItemAutoCadastroProdutos;
    private javax.swing.JMenuItem jMenuItemCadastrarAcervo;
    private javax.swing.JMenuItem jMenuItemCadastrarAluno;
    private javax.swing.JMenuItem jMenuItemCadastrarAlunoClasse;
    private javax.swing.JMenuItem jMenuItemCadastrarClasse;
    private javax.swing.JMenuItem jMenuItemComercioRealizarVendas;
    private javax.swing.JMenuItem jMenuItemConsultarAcervo;
    private javax.swing.JMenuItem jMenuItemConsultarListaTelefonica;
    private javax.swing.JMenuItem jMenuItemConsultarTombo;
    private javax.swing.JMenuItem jMenuItemFonoaudiologoRelatorioIndividualAluno;
    private javax.swing.JMenuItem jMenuItemInformaticaCadastroEquipamento;
    private javax.swing.JMenuItem jMenuItemListarAniversario;
    private javax.swing.JMenuItem jMenuItemLoginSenha;
    private javax.swing.JMenuItem jMenuItemPessoaNM;
    private javax.swing.JMenuItem jMenuItemProfessorPRS;
    private javax.swing.JMenuItem jMenuItemProfessorRelatorioAluno;
    private javax.swing.JMenuItem jMenuItemProfessoresEncamiamento;
    private javax.swing.JMenuItem jMenuItemProfessoresRelatorioClasse;
    private javax.swing.JMenuItem jMenuItemPsicologoRelatorioRelatorioIndividualdoAluno;
    private javax.swing.JMenuItem jMenuItemRelatarEntradaSaida;
    private javax.swing.JMenuItem jMenuItemSGSESair;
    private javax.swing.JMenuItem jMenuItemSecretariaConsultarListaTelefonica;
    private javax.swing.JMenuItem jMenuItemSecretariaImprimirRIAluno;
    private javax.swing.JMenu jMenuListar;
    private javax.swing.JMenu jMenuProfessorRelatorios;
    private javax.swing.JMenu jMenuProfessores;
    private javax.swing.JMenu jMenuPsicologaRelatorio;
    private javax.swing.JMenu jMenuPsicologo;
    private javax.swing.JMenu jMenuSGU;
    private javax.swing.JMenu jMenuSecretaria;
    private javax.swing.JMenu jMenuSecretariaCadastrar;
    private javax.swing.JMenu jMenuSecretariaConsultar;
    private javax.swing.JMenu jMenuSecretariaImprimir;
    // End of variables declaration//GEN-END:variables

    
}
