/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.escola;

import base.ctr.BaseCTR;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Douglas Estanislau Pereira
 */
public class BibliotecaConsultaAutorDIALOG extends javax.swing.JDialog {

    private String autor;
    
    /**
     * Creates new form BibliotecaConsultaAutorDIALOG
     */
    public BibliotecaConsultaAutorDIALOG(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableConsultarAutor = new javax.swing.JTable();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jRadioButtonAutor = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jButtonAddAutor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jTableConsultarAutor.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTableConsultarAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID:", "Autor:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableConsultarAutor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableConsultarAutor.getTableHeader().setReorderingAllowed(false);
        jTableConsultarAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultarAutorMouseClicked(evt);
            }
        });
        jTableConsultarAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableConsultarAutorKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableConsultarAutor);
        if (jTableConsultarAutor.getColumnModel().getColumnCount() > 0) {
            jTableConsultarAutor.getColumnModel().getColumn(0).setPreferredWidth(70);
            jTableConsultarAutor.getColumnModel().getColumn(1).setPreferredWidth(400);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 110, 830, 240);

        jTextFieldPesquisa.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisa);
        jTextFieldPesquisa.setBounds(90, 70, 470, 28);

        jRadioButtonAutor.setText("Nome:");
        jRadioButtonAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAutorActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonAutor);
        jRadioButtonAutor.setBounds(90, 40, 90, 24);

        jLabel1.setText("Pesquisar por:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 10, 120, 18);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/48x48/Sair48.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(0, 0, 80, 80);

        jButtonAddAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jButtonAddAutor.setToolTipText("Adicionar Autor");
        jButtonAddAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddAutorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddAutor);
        jButtonAddAutor.setBounds(560, 70, 30, 28);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Iniciar(){
        this.setSize(850, 375);
        this.setTitle("Biblioteca - Consultar Autor");
        jRadioButtonAutor.setSelected(true);
    }
    
    private void jTextFieldPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            Consultar();
        }
    }//GEN-LAST:event_jTextFieldPesquisaKeyPressed

    private void jRadioButtonAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAutorActionPerformed
        // TODO add your handling code here:
        jRadioButtonAutor.setSelected(true);
        jTextFieldPesquisa.setText("");
        jTextFieldPesquisa.requestFocus();
    }//GEN-LAST:event_jRadioButtonAutorActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        Sair();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        jTextFieldPesquisa.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    private void jButtonAddAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddAutorActionPerformed
        // TODO add your handling code here:
        InserirAutor();
        //ConsultarAutor();
    }//GEN-LAST:event_jButtonAddAutorActionPerformed

    private void jTableConsultarAutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultarAutorMouseClicked
        // TODO add your handling code here:
        ChaveSelecao();
    }//GEN-LAST:event_jTableConsultarAutorMouseClicked

    private void jTableConsultarAutorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableConsultarAutorKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER){
            ChaveSelecao();
        }
    }//GEN-LAST:event_jTableConsultarAutorKeyPressed

    public void InserirAutor(){
        try{
            BaseCTR inserirAutorCTR = new BaseCTR();
            String nome = JOptionPane.showInputDialog("Informe o Autor(a):","");
            if ("".equals(nome)){
                JOptionPane.showMessageDialog(null,"Campo em Branco. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                inserirAutorCTR.InserirAutor(nome.toUpperCase());
		JOptionPane.showMessageDialog(null,""+nome+" Inserido com Sucesso. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
                jTextFieldPesquisa.setText(nome);
                ConsultarAutor();
            }
	}
            catch(Exception e){
		System.out.println(e.getMessage());
	}
    }
    
    public void ChaveSelecao(){
        int linha = jTableConsultarAutor.getSelectedRow();
        setAutor(jTableConsultarAutor.getValueAt(linha,1).toString());
        this.dispose();
    }
    
    public void Consultar() {
        
        if (jRadioButtonAutor.isSelected() == true){
            ConsultarAutor();
        }
    }
    
    public void ConsultarAutor(){
        try{
            BaseCTR consultar = new BaseCTR();
            ResultSet rs=null;
            rs=consultar.ConsultarAutor(jTextFieldPesquisa.getText().toUpperCase());
            DefaultTableModel modelo = (DefaultTableModel) jTableConsultarAutor.getModel();
            modelo.setNumRows(0);
            while (rs.next()){
                Object[] novaLinha = new Object[2];
                novaLinha[0] = rs.getInt("autor_id");
                novaLinha[1] = rs.getString("autor_nome");
                modelo.addRow(novaLinha);
            }
        }
        catch (Exception e){
            System.out.println(e.getMessage());    
            }
    }
    
    public void Sair(){
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BibliotecaConsultaAutorDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BibliotecaConsultaAutorDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BibliotecaConsultaAutorDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BibliotecaConsultaAutorDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BibliotecaConsultaAutorDIALOG dialog = new BibliotecaConsultaAutorDIALOG(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddAutor;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButtonAutor;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableConsultarAutor;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the autor
     */
    public String getAutor() {
        return autor;
    }

    /**
     * @param autor the autor to set
     */
    public void setAutor(String autor) {
        this.autor = autor;
    }
}
