/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.escola;

import base.ctr.BaseCTR;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author administrador
 */
public class BibliotecaConsultaTomboDIALOG extends javax.swing.JDialog {

    /**
     * Creates new form BibliotecaConsultaTomboDIALOG
     */
    public BibliotecaConsultaTomboDIALOG(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableConsultarTombo = new javax.swing.JTable();
        jButtonSair = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTableConsultarTombo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTableConsultarTombo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID:", "ISBN:", "Tombo:", "Nome:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableConsultarTombo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableConsultarTombo.getTableHeader().setReorderingAllowed(false);
        jTableConsultarTombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultarTomboMouseClicked(evt);
            }
        });
        jTableConsultarTombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableConsultarTomboKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableConsultarTombo);
        if (jTableConsultarTombo.getColumnModel().getColumnCount() > 0) {
            jTableConsultarTombo.getColumnModel().getColumn(0).setPreferredWidth(70);
            jTableConsultarTombo.getColumnModel().getColumn(1).setPreferredWidth(140);
            jTableConsultarTombo.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableConsultarTombo.getColumnModel().getColumn(3).setPreferredWidth(600);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 110, 830, 240);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/48x48/Sair48.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(80, 0, 80, 80);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/48x48/Atualizar48.png"))); // NOI18N
        jButton1.setToolTipText("Atualizar Tabela...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 80, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableConsultarTomboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultarTomboMouseClicked
        // TODO add your handling code here:
        //ChaveSelecao();
    }//GEN-LAST:event_jTableConsultarTomboMouseClicked

    private void jTableConsultarTomboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableConsultarTomboKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER){
            //ChaveSelecao();
        }
    }//GEN-LAST:event_jTableConsultarTomboKeyPressed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        Sair();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ConsultarTombo();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void Iniciar(){
        this.setSize(850, 375);
        this.setTitle("Biblioteca - Consultar Tombo");
        //jRadioButtonEditora.setSelected(true);
        ConsultarTombo();
    }
    
    public void ConsultarTombo(){
        try{
            BaseCTR consultar = new BaseCTR();
            ResultSet rs=null;
            rs=consultar.ConsultarAcervoBibliotecaTombo2();
            DefaultTableModel modelo = (DefaultTableModel) jTableConsultarTombo.getModel();
            modelo.setNumRows(0);
            while (rs.next()){
                Object[] novaLinha = new Object[4];
                novaLinha[0] = rs.getInt("acervo_tombo_empresa_id");
                novaLinha[1] = rs.getString("acervo_isbn");
                novaLinha[2] = rs.getString("acervo_tombo_empresa_numero");
                novaLinha[3] = rs.getString("acervo_nome");
                modelo.addRow(novaLinha);
            }
        }
        catch (Exception e){
            System.out.println(e.getMessage());    
            }
    }
    
    public void Sair(){
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BibliotecaConsultaTomboDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BibliotecaConsultaTomboDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BibliotecaConsultaTomboDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BibliotecaConsultaTomboDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BibliotecaConsultaTomboDIALOG dialog = new BibliotecaConsultaTomboDIALOG(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableConsultarTombo;
    // End of variables declaration//GEN-END:variables
}
