/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.escola;

import base.ctr.BaseCTR;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Douglas Estanislau Pereira
 */
public class BibliotecaConsultaTagDIALOG extends javax.swing.JDialog {
    
    private String tag;

    /**
     * Creates new form BibliotecaConsultarTagDIALOG
     */
    public BibliotecaConsultaTagDIALOG(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRadioButtonTag = new javax.swing.JRadioButton();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonAddTag = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableConsultarTag = new javax.swing.JTable();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Pesquisar por:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 10, 120, 18);

        jRadioButtonTag.setText("Nome:");
        jRadioButtonTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTagActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonTag);
        jRadioButtonTag.setBounds(90, 40, 90, 24);

        jTextFieldPesquisa.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisa);
        jTextFieldPesquisa.setBounds(90, 70, 470, 28);

        jButtonAddTag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jButtonAddTag.setToolTipText("Adicionar Autor");
        jButtonAddTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTagActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddTag);
        jButtonAddTag.setBounds(560, 70, 30, 28);

        jTableConsultarTag.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTableConsultarTag.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID:", "Editora:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableConsultarTag.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableConsultarTag.getTableHeader().setReorderingAllowed(false);
        jTableConsultarTag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultarTagMouseClicked(evt);
            }
        });
        jTableConsultarTag.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableConsultarTagKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableConsultarTag);
        if (jTableConsultarTag.getColumnModel().getColumnCount() > 0) {
            jTableConsultarTag.getColumnModel().getColumn(0).setPreferredWidth(70);
            jTableConsultarTag.getColumnModel().getColumn(1).setPreferredWidth(500);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 110, 830, 240);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/48x48/Sair48.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(0, 0, 80, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTagActionPerformed
        // TODO add your handling code here:
        jRadioButtonTag.setSelected(true);
        jTextFieldPesquisa.setText("");
        jTextFieldPesquisa.requestFocus();
    }//GEN-LAST:event_jRadioButtonTagActionPerformed

    public void Sair(){
        this.dispose();
    }
    
    public void Iniciar(){
        this.setSize(850, 375);
        this.setTitle("Biblioteca - Consultar Editora");
        jRadioButtonTag.setSelected(true);
    }
    
    public void InserirTag(){
        try{
            BaseCTR inserirTagCTR = new BaseCTR();
            String tag = JOptionPane.showInputDialog("Informe o Tag:","");
            if ("".equals(tag)){
                JOptionPane.showMessageDialog(null,"Campo em Branco. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                inserirTagCTR.InserirTag(tag.toUpperCase());
		JOptionPane.showMessageDialog(null,""+tag+" Inserido com Sucesso. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
                jTextFieldPesquisa.setText(tag);
                ConsultarTag();
            }
	}
            catch(Exception e){
		System.out.println(e.getMessage());
	}
    }
        
    public void ChaveSelecao(){
        int linha = jTableConsultarTag.getSelectedRow();
        setTag(jTableConsultarTag.getValueAt(linha,1).toString());
        this.dispose();
    }
    
    public void Consultar() {
        if (jRadioButtonTag.isSelected() == true){
            ConsultarTag();
        }
    }
    
     public void ConsultarTag(){
        try{
            BaseCTR consultar = new BaseCTR();
            ResultSet rs=null;
            //rs=consultar.ConsultarTag(jTextFieldPesquisa.getText().toUpperCase());
            rs= consultar.ConsultarTag(jTextFieldPesquisa.getText().toUpperCase());
            DefaultTableModel modelo = (DefaultTableModel) jTableConsultarTag.getModel();
            modelo.setNumRows(0);
            while (rs.next()){
                Object[] novaLinha = new Object[2];
                novaLinha[0] = rs.getInt("tag_id");
                novaLinha[1] = rs.getString("tag_nome");
                modelo.addRow(novaLinha);
            }
        }
        catch (Exception e){
            System.out.println(e.getMessage());    
            }
    }
    
    private void jTextFieldPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            Consultar();
        }
    }//GEN-LAST:event_jTextFieldPesquisaKeyPressed

    private void jButtonAddTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTagActionPerformed
        // TODO add your handling code here:
        InserirTag();
        //ConsultarAutor();
    }//GEN-LAST:event_jButtonAddTagActionPerformed

    private void jTableConsultarTagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultarTagMouseClicked
        // TODO add your handling code here:
        ChaveSelecao();
    }//GEN-LAST:event_jTableConsultarTagMouseClicked

    private void jTableConsultarTagKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableConsultarTagKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER){
            ChaveSelecao();
        }
    }//GEN-LAST:event_jTableConsultarTagKeyPressed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        Sair();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        jTextFieldPesquisa.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BibliotecaConsultaTagDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BibliotecaConsultaTagDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BibliotecaConsultaTagDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BibliotecaConsultaTagDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BibliotecaConsultaTagDIALOG dialog = new BibliotecaConsultaTagDIALOG(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddTag;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButtonTag;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableConsultarTag;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tag
     */
    public String getTag() {
        return tag;
    }

    /**
     * @param tag the tag to set
     */
    public void setTag(String tag) {
        this.tag = tag;
    }
}
