/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.escola;

import base.ctr.BaseCTR;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Douglas Estanislau Pereira
 */
public class BibliotecaConsultaColecaoDIALOG extends javax.swing.JDialog {
    
    private String colecao;

    /**
     * Creates new form BibliotecaConsultaColecaoDialog
     */
    public BibliotecaConsultaColecaoDIALOG(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRadioButtonNome = new javax.swing.JRadioButton();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableConsultaBiblioteca = new javax.swing.JTable();
        jButtonSair = new javax.swing.JButton();
        jButtonAddColecao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Pesquisar por:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 10, 120, 18);

        jRadioButtonNome.setText("Nome");
        jRadioButtonNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonNome);
        jRadioButtonNome.setBounds(90, 40, 80, 24);

        jTextFieldPesquisa.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisa);
        jTextFieldPesquisa.setBounds(90, 70, 470, 28);

        jTableConsultaBiblioteca.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTableConsultaBiblioteca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID:", "Coleção:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableConsultaBiblioteca.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableConsultaBiblioteca.getTableHeader().setReorderingAllowed(false);
        jTableConsultaBiblioteca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultaBibliotecaMouseClicked(evt);
            }
        });
        jTableConsultaBiblioteca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableConsultaBibliotecaKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableConsultaBiblioteca);
        if (jTableConsultaBiblioteca.getColumnModel().getColumnCount() > 0) {
            jTableConsultaBiblioteca.getColumnModel().getColumn(0).setPreferredWidth(70);
            jTableConsultaBiblioteca.getColumnModel().getColumn(1).setPreferredWidth(400);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 110, 830, 240);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/48x48/Sair48.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(0, 0, 80, 80);

        jButtonAddColecao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jButtonAddColecao.setToolTipText("Adicionar Autor");
        jButtonAddColecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddColecaoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAddColecao);
        jButtonAddColecao.setBounds(560, 70, 30, 28);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Iniciar() {
       this.setSize(850, 375);
       this.setTitle("Biblioteca - Consultar Coleção");
       jRadioButtonNome.setSelected(true);
    }

    public void Sair() {
        this.dispose();
    }
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
       jTextFieldPesquisa.requestFocus(); 
    }//GEN-LAST:event_formWindowActivated

    private void jRadioButtonNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNomeActionPerformed
        // TODO add your handling code here:
        //jRadioButtonAutor.setSelected(false);
        //jRadioButtonColecao.setSelected(false);
        //jRadioButtonEditora.setSelected(false);
        jRadioButtonNome.setSelected(true);
        //jRadioButtonSubTitulo.setSelected(false);
        //jRadioButtonTag.setSelected(false);
        //jRadioButtonTitulo.setSelected(false);
        //jRadioButtonTombo.setSelected(false);
        jTextFieldPesquisa.setText("");
        jTextFieldPesquisa.requestFocus();
    }//GEN-LAST:event_jRadioButtonNomeActionPerformed

    private void jTextFieldPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            Consultar();
        }
    }//GEN-LAST:event_jTextFieldPesquisaKeyPressed

    private void jTableConsultaBibliotecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultaBibliotecaMouseClicked
        // TODO add your handling code here:
        ChaveSelecao();
    }//GEN-LAST:event_jTableConsultaBibliotecaMouseClicked

    private void jTableConsultaBibliotecaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableConsultaBibliotecaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER){
            ChaveSelecao();
        }
    }//GEN-LAST:event_jTableConsultaBibliotecaKeyPressed

    public void Consultar() {
        if (jRadioButtonNome.isSelected() == true){
            ConsultarColecao();
        }
    }
    
    public void ConsultarColecao(){
        try{
            BaseCTR consultar = new BaseCTR();
            ResultSet rs=null;
            rs=consultar.ConsultarColecao(jTextFieldPesquisa.getText().toUpperCase());
            DefaultTableModel modelo = (DefaultTableModel) jTableConsultaBiblioteca.getModel();
            modelo.setNumRows(0);
            while (rs.next()){
                Object[] novaLinha = new Object[2];
                novaLinha[0] = rs.getInt("acervo_colecao_id");
                novaLinha[1] = rs.getString("acervo_colecao_nome");
                modelo.addRow(novaLinha);
            }
        }
        catch (Exception e){
            System.out.println(e.getMessage());    
            }
    }
    
    public void ChaveSelecao(){
        int linha = jTableConsultaBiblioteca.getSelectedRow();
        //setGetcolecaoid(jTableConsultaBiblioteca.getValueAt(linha,0).toString());
        setGetcolecao(jTableConsultaBiblioteca.getValueAt(linha,1).toString());
        //setGettitulo(jTableConsultaBiblioteca.getValueAt(linha,2).toString());
        this.dispose();
    }
    
    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        Sair();
    }//GEN-LAST:event_jButtonSairActionPerformed

    public void InserirColecao(){
        try{
            BaseCTR inserirColecaoCTR = new BaseCTR();
            String colecao = JOptionPane.showInputDialog("Informe a Coleção:","");
            if ("".equals(colecao)){
                JOptionPane.showMessageDialog(null,"Campo em Branco. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                inserirColecaoCTR.InserirColecao(colecao.toUpperCase());
		JOptionPane.showMessageDialog(null,""+colecao+" Inserido com Sucesso. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
                //jTextFieldPesquisa.setText("");
                jTextFieldPesquisa.setText(colecao);
                ConsultarColecao();
            }
	}
            catch(Exception e){
		System.out.println(e.getMessage());
	}
    }
    
    private void jButtonAddColecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddColecaoActionPerformed
        // TODO add your handling code here:
        InserirColecao();
        //ConsultarAutor();
    }//GEN-LAST:event_jButtonAddColecaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BibliotecaConsultaColecaoDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BibliotecaConsultaColecaoDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BibliotecaConsultaColecaoDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BibliotecaConsultaColecaoDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BibliotecaConsultaColecaoDIALOG dialog = new BibliotecaConsultaColecaoDIALOG(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddColecao;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButtonNome;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableConsultaBiblioteca;
    private javax.swing.JTextField jTextFieldPesquisa;
    // End of variables declaration//GEN-END:variables

/**
     * @return the coleção
     */
    public String getColecao() {
        return colecao;
    }

    /**
     * @param coleção the autor to set
     */
    public void setGetcolecao(String colecao) {
        this.colecao = colecao;
    }

}
