/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.escola;

import base.ctr.BaseCTR;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Douglas Estanislau Pereira
 */
public class BibliotecaRelatarVIEW extends javax.swing.JInternalFrame {

    public String relatarboolean;
    //BibliotecaCTR biblioteca = new EscolaCTR();
    
    /**
     * Creates new form BibliotecaRelatarVIEW
     */
    public BibliotecaRelatarVIEW() {
        initComponents();
        Iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRelatarEntradaSaida = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTombo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTomboTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxUF = new javax.swing.JComboBox();
        jTextFieldPessoaRA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPessoaNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRelatarAcervo = new javax.swing.JTable();
        jLabelAutorCodigo1 = new javax.swing.JLabel();
        jTextFieldRelatarEntradaCodigo = new javax.swing.JTextField();
        jRadioButtonAcervoaDevolver = new javax.swing.JRadioButton();
        jRadioButtonAcervoDevolvido = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldPesquisaAcervoRelato = new javax.swing.JTextField();
        jRadioButtonPesquisaNomeRA = new javax.swing.JRadioButton();
        jRadioButtonPesquisaTitulo = new javax.swing.JRadioButton();

        setMinimumSize(new java.awt.Dimension(800, 600));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jButtonRelatarEntradaSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/48x48/Gravar48.png"))); // NOI18N
        jButtonRelatarEntradaSaida.setToolTipText("Relata Entrada/Saída do Acervo");
        jButtonRelatarEntradaSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatarEntradaSaidaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRelatarEntradaSaida);
        jButtonRelatarEntradaSaida.setBounds(0, 0, 80, 80);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/48x48/Sair48.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(800, 0, 80, 80);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Tombo:   ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 14))); // NOI18N
        jPanel1.setToolTipText("");
        jPanel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 120, 650, 0);

        jLabel1.setText("Tombo:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 30, 80, 14);

        jTextFieldTombo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTextFieldTombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldTomboKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldTombo);
        jTextFieldTombo.setBounds(90, 50, 120, 26);

        jLabel2.setText("Título:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 30, 60, 14);

        jTextFieldTomboTitulo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        getContentPane().add(jTextFieldTomboTitulo);
        jTextFieldTomboTitulo.setBounds(220, 50, 520, 26);

        jLabel3.setText("UF:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 90, 40, 14);

        jComboBoxUF.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        getContentPane().add(jComboBoxUF);
        jComboBoxUF.setBounds(20, 110, 60, 26);

        jTextFieldPessoaRA.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTextFieldPessoaRA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPessoaRAKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldPessoaRA);
        jTextFieldPessoaRA.setBounds(90, 110, 120, 26);

        jLabel4.setText("Nome:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 90, 60, 14);

        jTextFieldPessoaNome.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        getContentPane().add(jTextFieldPessoaNome);
        jTextFieldPessoaNome.setBounds(220, 110, 520, 26);

        jLabel5.setText("RA/RG:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 90, 70, 14);

        jTableRelatarAcervo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTableRelatarAcervo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód.:", "Data Saída:", "Data Entrada:", "Dias:", "Tombo:", "Título:", "Nome:", "UF:", "RA/RG:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableRelatarAcervo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableRelatarAcervo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableRelatarAcervoMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRelatarAcervoMouseClicked(evt);
            }
        });
        jTableRelatarAcervo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableRelatarAcervoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableRelatarAcervo);
        if (jTableRelatarAcervo.getColumnModel().getColumnCount() > 0) {
            jTableRelatarAcervo.getColumnModel().getColumn(0).setResizable(false);
            jTableRelatarAcervo.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableRelatarAcervo.getColumnModel().getColumn(1).setResizable(false);
            jTableRelatarAcervo.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableRelatarAcervo.getColumnModel().getColumn(2).setResizable(false);
            jTableRelatarAcervo.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableRelatarAcervo.getColumnModel().getColumn(3).setResizable(false);
            jTableRelatarAcervo.getColumnModel().getColumn(3).setPreferredWidth(30);
            jTableRelatarAcervo.getColumnModel().getColumn(4).setResizable(false);
            jTableRelatarAcervo.getColumnModel().getColumn(4).setPreferredWidth(80);
            jTableRelatarAcervo.getColumnModel().getColumn(5).setResizable(false);
            jTableRelatarAcervo.getColumnModel().getColumn(5).setPreferredWidth(300);
            jTableRelatarAcervo.getColumnModel().getColumn(6).setResizable(false);
            jTableRelatarAcervo.getColumnModel().getColumn(6).setPreferredWidth(300);
            jTableRelatarAcervo.getColumnModel().getColumn(7).setResizable(false);
            jTableRelatarAcervo.getColumnModel().getColumn(7).setPreferredWidth(30);
            jTableRelatarAcervo.getColumnModel().getColumn(8).setResizable(false);
            jTableRelatarAcervo.getColumnModel().getColumn(8).setPreferredWidth(100);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 260, 870, 260);

        jLabelAutorCodigo1.setText("Código:");
        getContentPane().add(jLabelAutorCodigo1);
        jLabelAutorCodigo1.setBounds(20, 530, 60, 14);

        jTextFieldRelatarEntradaCodigo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTextFieldRelatarEntradaCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRelatarEntradaCodigoKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldRelatarEntradaCodigo);
        jTextFieldRelatarEntradaCodigo.setBounds(80, 530, 60, 26);

        jRadioButtonAcervoaDevolver.setText("Acervo a Devolver");
        jRadioButtonAcervoaDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAcervoaDevolverActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonAcervoaDevolver);
        jRadioButtonAcervoaDevolver.setBounds(430, 230, 115, 23);

        jRadioButtonAcervoDevolvido.setText("Acervo Devolvido");
        jRadioButtonAcervoDevolvido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAcervoDevolvidoActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonAcervoDevolvido);
        jRadioButtonAcervoDevolvido.setBounds(600, 230, 170, 23);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 150, 750, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(10, 220, 750, 10);

        jTextFieldPesquisaAcervoRelato.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTextFieldPesquisaAcervoRelato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaAcervoRelatoKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldPesquisaAcervoRelato);
        jTextFieldPesquisaAcervoRelato.setBounds(190, 170, 550, 26);

        jRadioButtonPesquisaNomeRA.setText("Nome do RA/RG:");
        jRadioButtonPesquisaNomeRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPesquisaNomeRAActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonPesquisaNomeRA);
        jRadioButtonPesquisaNomeRA.setBounds(20, 160, 160, 23);

        jRadioButtonPesquisaTitulo.setText("Título do Tombo:");
        jRadioButtonPesquisaTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPesquisaTituloActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonPesquisaTitulo);
        jRadioButtonPesquisaTitulo.setBounds(20, 190, 160, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRelatarEntradaSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatarEntradaSaidaActionPerformed
       //RelatarSaida();
        RelatarEntradaSaida();
    }//GEN-LAST:event_jButtonRelatarEntradaSaidaActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        Sair();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jRadioButtonAcervoaDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAcervoaDevolverActionPerformed
        // TODO add your handling code here:
        jRadioButtonAcervoaDevolver.setSelected(true);
        jRadioButtonAcervoDevolvido.setSelected(false);
        ConsultarRelatarAcervo();
        
    }//GEN-LAST:event_jRadioButtonAcervoaDevolverActionPerformed

    private void jRadioButtonAcervoDevolvidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAcervoDevolvidoActionPerformed
        // TODO add your handling code here:
        jRadioButtonAcervoaDevolver.setSelected(false);
        jRadioButtonAcervoDevolvido.setSelected(true);
        ConsultarRelatarAcervo();
        
    }//GEN-LAST:event_jRadioButtonAcervoDevolvidoActionPerformed

    private void jRadioButtonPesquisaNomeRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPesquisaNomeRAActionPerformed
        // TODO add your handling code here:
        jRadioButtonPesquisaTitulo.setSelected(false);
        jRadioButtonPesquisaNomeRA.setSelected(true);
        jTextFieldPesquisaAcervoRelato.setText("");
        jTextFieldPesquisaAcervoRelato.requestFocus();
    }//GEN-LAST:event_jRadioButtonPesquisaNomeRAActionPerformed

    private void jRadioButtonPesquisaTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPesquisaTituloActionPerformed
        // TODO add your handling code here:
        jRadioButtonPesquisaTitulo.setSelected(true);
        jRadioButtonPesquisaNomeRA.setSelected(false);
        jTextFieldPesquisaAcervoRelato.setText("");
        jTextFieldPesquisaAcervoRelato.requestFocus();
    }//GEN-LAST:event_jRadioButtonPesquisaTituloActionPerformed

    private void jTextFieldPesquisaAcervoRelatoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaAcervoRelatoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            ConsultarRelatarAcervo();
        }
    }//GEN-LAST:event_jTextFieldPesquisaAcervoRelatoKeyPressed

    private void jTextFieldTomboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTomboKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER){  
            //ConsultarVerificadorTombo();
            ConsultarRelatoEntradaSaida();
            //jButtonRelatarEntradaSaida.doClick();
        } 
    }//GEN-LAST:event_jTextFieldTomboKeyPressed

    private void jTextFieldPessoaRAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPessoaRAKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER){
        ConsultarVerificadorPessoa();
        jTextFieldTombo.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldPessoaRAKeyPressed

    private void jTextFieldRelatarEntradaCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRelatarEntradaCodigoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER){
            RelatarEntrada();
        }
    }//GEN-LAST:event_jTextFieldRelatarEntradaCodigoKeyPressed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        jTextFieldPessoaRA.requestFocus();
    }//GEN-LAST:event_formInternalFrameActivated

    private void jTableRelatarAcervoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRelatarAcervoMouseClicked
        // TODO add your handling code here:
        //ChaveSelecao();
    }//GEN-LAST:event_jTableRelatarAcervoMouseClicked

    private void jTableRelatarAcervoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableRelatarAcervoKeyPressed
        // TODO add your handling code here:
        //ChaveSelecao();
    }//GEN-LAST:event_jTableRelatarAcervoKeyPressed

    private void jTableRelatarAcervoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRelatarAcervoMousePressed
        // TODO add your handling code here:
        ChaveSelecao();
    }//GEN-LAST:event_jTableRelatarAcervoMousePressed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRelatarEntradaSaida;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox jComboBoxUF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAutorCodigo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonAcervoDevolvido;
    private javax.swing.JRadioButton jRadioButtonAcervoaDevolver;
    private javax.swing.JRadioButton jRadioButtonPesquisaNomeRA;
    private javax.swing.JRadioButton jRadioButtonPesquisaTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableRelatarAcervo;
    private javax.swing.JTextField jTextFieldPesquisaAcervoRelato;
    private javax.swing.JTextField jTextFieldPessoaNome;
    private javax.swing.JTextField jTextFieldPessoaRA;
    private javax.swing.JTextField jTextFieldRelatarEntradaCodigo;
    private javax.swing.JTextField jTextFieldTombo;
    private javax.swing.JTextField jTextFieldTomboTitulo;
    // End of variables declaration//GEN-END:variables

    public void Iniciar() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
       this.setSize(900, 600);
       this.setTitle("Biblioteca - Relatar Entrada/Saída do Acervo");
       jRadioButtonAcervoaDevolver.setSelected(true);
       jRadioButtonPesquisaNomeRA.setSelected(true);
       jTextFieldTomboTitulo.setEditable(false);
       jTextFieldPessoaNome.setEditable(false);
       ConsultarUF();
       ConsultarRelatarAcervo();
    }

    public void Sair() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        this.dispose();
    }
    
    public void ChaveSelecao(){
        int linha = jTableRelatarAcervo.getSelectedRow();
        jTextFieldRelatarEntradaCodigo.setText("");
        jTextFieldRelatarEntradaCodigo.setText(jTableRelatarAcervo.getValueAt(linha,0).toString());
        jButtonRelatarEntradaSaida.doClick();
    } 
    
    public void LimparCampos(){
        jTextFieldPessoaNome.setText("");
        jTextFieldPessoaRA.setText("");
        jTextFieldTombo.setText("");
        jTextFieldTomboTitulo.setText("");
        jTextFieldRelatarEntradaCodigo.setText("");
    }
    
    public void LimparCampos2(){
        jTextFieldPessoaNome.setText("");
        jTextFieldPessoaRA.setText("");
        //jTextFieldTombo.setText("");
        jTextFieldTomboTitulo.setText("");
        //jTextFieldRelatarEntradaCodigo.setText("");
    }
    
    public void ConsultarRelatarAcervoPessoa(){
        try{
            BaseCTR consultar = new BaseCTR();
            ResultSet rs=null;
            rs=consultar.ConsultarRelatarAcervoPessoa(relatarboolean, jTextFieldPesquisaAcervoRelato.getText().toUpperCase());
            DefaultTableModel modelo = (DefaultTableModel) jTableRelatarAcervo.getModel();
            modelo.setNumRows(0);
            while (rs.next()){
                Object[] novaLinha = new Object[9];
                novaLinha[0] = rs.getString("acervo_relatar_id");
                novaLinha[1] = rs.getString("acervo_relatar_data");
                novaLinha[2] = rs.getString("acervo_relatar_data_saida");
                novaLinha[3] = rs.getString("dias");
                novaLinha[4] = rs.getString("acervo_tombo_empresa_numero");
                novaLinha[5] = rs.getString("acervo_nome");
                novaLinha[6] = rs.getString("pessoa_nome");
                novaLinha[7] = rs.getString("pessoa_ci_uf");
                novaLinha[8] = rs.getString("pessoa_ci_numero");
                modelo.addRow(novaLinha);
            }
        }
        catch (Exception e){
            System.out.println(e.getMessage());    
            }
    }
    
    public void ConsultarRelatarAcervoTombo(){
        try{
            BaseCTR consultar = new BaseCTR();
            ResultSet rs=null;
            rs=consultar.ConsultarRelatarAcervoTombo(relatarboolean, jTextFieldPesquisaAcervoRelato.getText().toUpperCase());
            DefaultTableModel modelo = (DefaultTableModel) jTableRelatarAcervo.getModel();
            modelo.setNumRows(0);
            while (rs.next()){
                Object[] novaLinha = new Object[9];
                novaLinha[0] = rs.getString("acervo_relatar_id");
                novaLinha[1] = rs.getString("acervo_relatar_data");
                novaLinha[2] = rs.getString("acervo_relatar_data_saida");
                novaLinha[3] = rs.getString("dias");
                novaLinha[4] = rs.getString("acervo_tombo_empresa_numero");
                novaLinha[5] = rs.getString("acervo_nome");
                novaLinha[6] = rs.getString("pessoa_nome");
                novaLinha[7] = rs.getString("pessoa_ci_uf");
                novaLinha[8] = rs.getString("pessoa_ci_numero");
                modelo.addRow(novaLinha);
            }
        }
        catch (Exception e){
            System.out.println(e.getMessage());    
        }
    }
    
    public void ConsultarRelatarAcervo(){
        if (jRadioButtonPesquisaNomeRA.isSelected() && jRadioButtonAcervoaDevolver.isSelected()){
            relatarboolean = "true";
            ConsultarRelatarAcervoPessoa();
        }
        if (jRadioButtonPesquisaNomeRA.isSelected() && jRadioButtonAcervoDevolvido.isSelected()){
            relatarboolean = "false";
            ConsultarRelatarAcervoPessoa();
        }
        if (jRadioButtonPesquisaTitulo.isSelected() && jRadioButtonAcervoaDevolver.isSelected()){
            relatarboolean = "true";
            ConsultarRelatarAcervoTombo();
        }
        if (jRadioButtonPesquisaTitulo.isSelected() && jRadioButtonAcervoDevolvido.isSelected()){
            relatarboolean = "false";
            ConsultarRelatarAcervoTombo();
        }
    }
    
    public void ConsultarRelatarTomboTitulo(){
        try{
            BaseCTR consultar = new BaseCTR();
            ResultSet rs=null;
            rs=consultar.ConsultarRelatarTomboTitulo(jTextFieldTombo.getText().toUpperCase());
            while (rs.next()){
                jTextFieldTomboTitulo.setText((rs.getString("acervo_nome")));
            }
        }
        catch (Exception e){
            System.out.println(e.getMessage());    
        }
    }
    
    public void ConsultarRelatarPessoaNome(){
        try{
            BaseCTR consultar = new BaseCTR();
            ResultSet rs=null;
            rs=consultar.ConsultarRelatarPessoaNome(jComboBoxUF.getSelectedItem().toString(), jTextFieldPessoaRA.getText().toUpperCase().replace(".", "").replace("-", ""));
            while (rs.next()){
                jTextFieldPessoaNome.setText((rs.getString("pessoa_nome")));
            }
        }
        catch (Exception e){
            System.out.println(e.getMessage());    
        }
    }
    
    public void ConsultarRelatarPessoaRA(ResultSet rs){
        try {
            
            if (rs.next()){
                jComboBoxUF.setSelectedItem(String.valueOf(rs.getString("pessoa_ci_uf")));
                jTextFieldPessoaRA.setText(String.valueOf(rs.getString("pessoa_ci_numero")));
                jTextFieldPessoaNome.setText(String.valueOf(rs.getString("pessoa_nome")));
                
            }else{
                JOptionPane.showMessageDialog(null,"RG/RA não encontrado! ","Informação",JOptionPane.INFORMATION_MESSAGE);
               }
            } 
        catch (Exception e){
            System.out.println(e.getMessage());    
         }
    }
    
    public void RelatarSaida(){
        try{
            BaseCTR relatarCTR = new BaseCTR();	
            if ("".equals(jTextFieldPessoaRA.getText()) || "".equals(jTextFieldTombo.getText())){
               JOptionPane.showMessageDialog(null,"Campo RG/RA ou Campo Tombo está Vazio, Verifique!. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);   
               jTextFieldTombo.requestFocus();
            }else{
                int i = JOptionPane.showConfirmDialog(null, "Deseja Relatar Saída do Acervo da Biblioteca? ","Informação: ", JOptionPane.YES_NO_OPTION);
                if(i == JOptionPane.YES_OPTION){
                    relatarCTR.InserirRelatarAcervo(jTextFieldTombo.getText().toUpperCase(),(String) jComboBoxUF.getSelectedItem(), jTextFieldPessoaRA.getText().toUpperCase().replace(".", "").replace("-", ""));
                    JOptionPane.showMessageDialog(null,"Foi Relatado a Saída com Sucesso do Acervo da Biblioteca. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
                    ConsultarRelatarAcervo();
                    LimparCampos();
                    jTextFieldPessoaRA.requestFocus();
                }
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Campos de Dados em Branco... ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
		System.out.println(e.getMessage());
            }
    }
    
    public void RelatarEntrada(){
        try{
            BaseCTR relatarCTR = new BaseCTR();	
            if ("".equals(jTextFieldRelatarEntradaCodigo.getText())){
               JOptionPane.showMessageDialog(null,"Campo Código está Vazio, Verifique!. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);   
               jTextFieldRelatarEntradaCodigo.requestFocus();
            }else{
                int i = JOptionPane.showConfirmDialog(null, "Deseja Relatar Entrada do Acervo a Biblioteca? ","Informação: ", JOptionPane.YES_NO_OPTION);
                if(i == JOptionPane.YES_OPTION){
                    relatarCTR.RemoverRelatarAcervo(Integer.parseInt(jTextFieldRelatarEntradaCodigo.getText()));
                    JOptionPane.showMessageDialog(null,"Foi Relatado a Entrada com Sucesso do Acervo. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
                    ConsultarRelatarAcervo();
                    LimparCampos();
                    jTextFieldRelatarEntradaCodigo.requestFocus();
                }
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Campos de Dados em Branco... ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
		System.out.println(e.getMessage());
	}
    }
    
    public void RelatarEntradaSaida(){
        if ("".equals(jTextFieldRelatarEntradaCodigo.getText())){
            RelatarSaida();
        }
        else{
            RelatarEntrada();
        }
    }
   
    public void ConsultarVerificadorPessoa(){
        try{
            BaseCTR consultarCTR = new BaseCTR();
            ResultSet rs=null;
            rs=consultarCTR.VerificadorRelatarPessoa((String) jComboBoxUF.getSelectedItem(), jTextFieldPessoaRA.getText().toUpperCase().replace(".", "").replace("-", ""));
            int v = 0;
            while(rs.next()){       
                v = (rs.getInt("verificador"));  
            }
            if (v == 0){
                JOptionPane.showMessageDialog(null,"RG/RA não encontrado ou não existente. Verifique...","Informação: ",JOptionPane.INFORMATION_MESSAGE);
                jTextFieldPessoaRA.setText("");
                jTextFieldPessoaNome.setText("");
                jTextFieldPessoaRA.requestFocus();
                
                AlunoConsultaDIALOG  jDialog = new AlunoConsultaDIALOG(null, true);
                jDialog.setModal(true);
                jDialog.setVisible(true);
                jComboBoxUF.setSelectedItem(jDialog.getGetuf());
                jTextFieldPessoaRA.setText(jDialog.getGetid());
                jTextFieldPessoaNome.setText(jDialog.getGetnome());
            }else{
                ConsultarRelatarPessoaNome();
            }
         }
         catch (Exception e){
            System.out.println(e.getMessage());    
         }
    }
     
    public void ConsultarRelatarTombo(){
        try{
            BaseCTR consultarCTR = new BaseCTR();
            ResultSet rs=null;
            rs=consultarCTR.ConsultarRelatarTombo(jTextFieldTombo.getText().toUpperCase());
            int v = 0;
            while(rs.next()){       
                jTextFieldRelatarEntradaCodigo.setText(rs.getString("acervo_relatar_id"));
                jComboBoxUF.setSelectedItem(rs.getString("pessoa_ci_uf"));
                jTextFieldPessoaRA.setText(rs.getString("pessoa_ci_numero"));
                jTextFieldPessoaNome.setText(rs.getString("pessoa_nome"));
                //jTextFieldTombo.setText(rs.getString("acervo_tombo_empresa_numero"));
                jTextFieldTomboTitulo.setText(rs.getString("acervo_nome"));
            }
        }
        catch (Exception e){
            System.out.println(e.getMessage());    
            }
    }
    
    
    public void ConsultarRelatoEntradaSaida(){
        try{
            BaseCTR consultarCTR = new BaseCTR();
            ResultSet rs=null;
            rs=consultarCTR.ConsultarRelatoEntradaSaida(jTextFieldTombo.getText().toUpperCase());
            int v = 0;
            while(rs.next()){       
                v = (rs.getInt("verificador"));  
            }
            if (v >= 1 ){
                JOptionPane.showMessageDialog(null,"Acervo já Emprestado. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
                LimparCampos2();
                ConsultarRelatarTombo();
                RelatarEntrada();
                jTextFieldRelatarEntradaCodigo.setText("");
                jTextFieldTombo.requestFocus();
            }else{
                ConsultarVerificadorTombo();
            }
            
        }
        catch (Exception e){
            System.out.println(e.getMessage());    
            }
    }
    
    
    public void ConsultarVerificadorTombo(){
        try{
            BaseCTR consultarCTR = new BaseCTR();
            ResultSet rs=null;
            rs=consultarCTR.VerificadorRelatarTombo(jTextFieldTombo.getText().toUpperCase());
            int v = 0;
            while(rs.next()){       
                v = (rs.getInt("verificador"));  
            }
            if (v == 0){
                JOptionPane.showMessageDialog(null,"Tombo não encontrado ou não existente. Verifique...","Informação: ",JOptionPane.INFORMATION_MESSAGE);
                jTextFieldTombo.setText("");
                jTextFieldTomboTitulo.setText("");
                jTextFieldTombo.requestFocus();
                
                BibliotecaConsultaDIALOG  jDialog = new BibliotecaConsultaDIALOG(null, true);
                jDialog.setModal(true);
                jDialog.setVisible(true);
                jTextFieldTombo.setText(jDialog.getGettombo());
                jTextFieldTomboTitulo.setText(jDialog.getGettitulo());
            }
            if (v >= 2){
                JOptionPane.showMessageDialog(null,"Existe Acervo com o mesmo Tombo. Verifique...","Informação: ",JOptionPane.INFORMATION_MESSAGE);
                jTextFieldTombo.setText("");
                jTextFieldTomboTitulo.setText("");
                jTextFieldTombo.requestFocus();
                
                BibliotecaConsultaDIALOG  jDialog = new BibliotecaConsultaDIALOG(null, true);
                jDialog.setModal(true);
                jDialog.setVisible(true);
                jTextFieldTombo.setText(jDialog.getGettombo());
                jTextFieldTomboTitulo.setText(jDialog.getGettitulo());
            }else{
                ConsultarRelatarTomboTitulo();
            }
         }
         catch (Exception e){
            System.out.println(e.getMessage());    
            }
        
    }
    
    public void ConsultarUF(){
        try{
            BaseCTR consultarCTR = new BaseCTR();
            ResultSet rs=null;
            rs=consultarCTR.ConsultarUF();
            jComboBoxUF.removeAllItems();
            while(rs.next()){       
                jComboBoxUF.addItem(rs.getString("uf_nome"));       
            }
         }
         catch (Exception e){
            System.out.println(e.getMessage());    
            }
    }
    
}
