/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.escola;

import base.ctr.BaseCTR;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Douglas Estanislau Pereira
 */
public class ClasseCadastroVIEW extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClasseCadastroVIEW
     */
    public ClasseCadastroVIEW() {
        initComponents();
        Iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalvar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelClasse = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldClasseNumero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxAnoLetivo = new javax.swing.JComboBox();
        jButtonAddAnoLetivo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxTipoEnsino = new javax.swing.JComboBox();
        jButtonAddTipoEnsino = new javax.swing.JButton();
        jButtonConsultarSerie = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxSerie = new javax.swing.JComboBox();
        jButtonAddSerie = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldHorarioInicio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldHorarioFim = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxSala = new javax.swing.JComboBox();
        jButtonAddSala = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxPeriodo = new javax.swing.JComboBox();
        jButtonAddPeriodo = new javax.swing.JButton();
        jButtonConsultarTurma = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxTurma = new javax.swing.JComboBox();
        jButtonAddTurma = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldClasseObs = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableClasse = new javax.swing.JTable();
        jButtonConsultarClasseAno = new javax.swing.JButton();
        jPanelGradeCurricular = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxDisciplina = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxProfessorUF = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldProfessorRG = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldProfessorNome = new javax.swing.JTextField();
        jTextFieldCargaHoraria = new javax.swing.JTextField();
        jPanelAlunoClasse = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxUF = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldRA = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldNomeCompleto = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jComboBoxSituacao = new javax.swing.JComboBox();
        jButtonAddSituacao = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jComboBoxDef = new javax.swing.JComboBox();
        jTextFieldObs = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlunonaClasse = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldTransf = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldRem = new javax.swing.JTextField();
        jComboBoxNChamada = new javax.swing.JComboBox();
        jButtonPesquisar = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/48x48/Gravar48.png"))); // NOI18N
        jButtonSalvar.setToolTipText("Relata Entrada/Saída do Acervo");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar);
        jButtonSalvar.setBounds(0, 0, 80, 80);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/48x48/Sair48.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(160, 0, 80, 80);

        jPanelClasse.setLayout(null);

        jLabel1.setText("Número:");
        jPanelClasse.add(jLabel1);
        jLabel1.setBounds(10, 10, 70, 18);

        jTextFieldClasseNumero.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTextFieldClasseNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldClasseNumeroKeyPressed(evt);
            }
        });
        jPanelClasse.add(jTextFieldClasseNumero);
        jTextFieldClasseNumero.setBounds(10, 30, 100, 28);

        jLabel2.setText("Ano Letivo:");
        jPanelClasse.add(jLabel2);
        jLabel2.setBounds(120, 10, 90, 18);

        jComboBoxAnoLetivo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelClasse.add(jComboBoxAnoLetivo);
        jComboBoxAnoLetivo.setBounds(120, 30, 70, 28);

        jButtonAddAnoLetivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jButtonAddAnoLetivo.setToolTipText("");
        jButtonAddAnoLetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddAnoLetivoActionPerformed(evt);
            }
        });
        jPanelClasse.add(jButtonAddAnoLetivo);
        jButtonAddAnoLetivo.setBounds(190, 30, 30, 28);

        jLabel3.setText("Tipo de Ensino:");
        jPanelClasse.add(jLabel3);
        jLabel3.setBounds(260, 10, 130, 18);

        jComboBoxTipoEnsino.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelClasse.add(jComboBoxTipoEnsino);
        jComboBoxTipoEnsino.setBounds(260, 30, 220, 28);

        jButtonAddTipoEnsino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jButtonAddTipoEnsino.setToolTipText("");
        jButtonAddTipoEnsino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTipoEnsinoActionPerformed(evt);
            }
        });
        jPanelClasse.add(jButtonAddTipoEnsino);
        jButtonAddTipoEnsino.setBounds(480, 30, 30, 28);

        jButtonConsultarSerie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/consultar16.png"))); // NOI18N
        jButtonConsultarSerie.setToolTipText("");
        jButtonConsultarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarSerieActionPerformed(evt);
            }
        });
        jPanelClasse.add(jButtonConsultarSerie);
        jButtonConsultarSerie.setBounds(520, 30, 30, 28);

        jLabel4.setText("Série:");
        jPanelClasse.add(jLabel4);
        jLabel4.setBounds(550, 10, 60, 18);

        jComboBoxSerie.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelClasse.add(jComboBoxSerie);
        jComboBoxSerie.setBounds(550, 30, 80, 28);

        jButtonAddSerie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jButtonAddSerie.setToolTipText("");
        jButtonAddSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSerieActionPerformed(evt);
            }
        });
        jPanelClasse.add(jButtonAddSerie);
        jButtonAddSerie.setBounds(630, 30, 30, 28);

        jLabel8.setText("Horário:");
        jPanelClasse.add(jLabel8);
        jLabel8.setBounds(260, 70, 70, 18);

        jTextFieldHorarioInicio.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelClasse.add(jTextFieldHorarioInicio);
        jTextFieldHorarioInicio.setBounds(260, 90, 80, 28);

        jLabel9.setText("às");
        jPanelClasse.add(jLabel9);
        jLabel9.setBounds(350, 100, 30, 18);

        jTextFieldHorarioFim.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelClasse.add(jTextFieldHorarioFim);
        jTextFieldHorarioFim.setBounds(380, 90, 80, 28);

        jLabel6.setText("Sala:");
        jPanelClasse.add(jLabel6);
        jLabel6.setBounds(150, 70, 40, 18);

        jComboBoxSala.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelClasse.add(jComboBoxSala);
        jComboBoxSala.setBounds(150, 90, 70, 28);

        jButtonAddSala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jButtonAddSala.setToolTipText("");
        jButtonAddSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSalaActionPerformed(evt);
            }
        });
        jPanelClasse.add(jButtonAddSala);
        jButtonAddSala.setBounds(220, 90, 30, 28);

        jLabel7.setText("Período:");
        jPanelClasse.add(jLabel7);
        jLabel7.setBounds(670, 10, 80, 18);

        jComboBoxPeriodo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelClasse.add(jComboBoxPeriodo);
        jComboBoxPeriodo.setBounds(670, 30, 150, 28);

        jButtonAddPeriodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jButtonAddPeriodo.setToolTipText("");
        jButtonAddPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPeriodoActionPerformed(evt);
            }
        });
        jPanelClasse.add(jButtonAddPeriodo);
        jButtonAddPeriodo.setBounds(820, 30, 30, 28);

        jButtonConsultarTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/consultar16.png"))); // NOI18N
        jButtonConsultarTurma.setToolTipText("");
        jButtonConsultarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarTurmaActionPerformed(evt);
            }
        });
        jPanelClasse.add(jButtonConsultarTurma);
        jButtonConsultarTurma.setBounds(10, 90, 30, 28);

        jLabel5.setText("Turma:");
        jPanelClasse.add(jLabel5);
        jLabel5.setBounds(40, 70, 80, 18);

        jComboBoxTurma.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelClasse.add(jComboBoxTurma);
        jComboBoxTurma.setBounds(40, 90, 70, 28);

        jButtonAddTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jButtonAddTurma.setToolTipText("");
        jButtonAddTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTurmaActionPerformed(evt);
            }
        });
        jPanelClasse.add(jButtonAddTurma);
        jButtonAddTurma.setBounds(110, 90, 30, 28);

        jLabel10.setText("Obs:");
        jPanelClasse.add(jLabel10);
        jLabel10.setBounds(470, 70, 60, 18);

        jTextFieldClasseObs.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelClasse.add(jTextFieldClasseObs);
        jTextFieldClasseObs.setBounds(470, 90, 380, 28);

        jTableClasse.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTableClasse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número:", "Ano Letivo:", "Tipo de Ensino:", "Série:", "Turma:", "Período:", "Sala:", "H. Início:", "H. Fim:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClasse.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableClasse.getTableHeader().setReorderingAllowed(false);
        jTableClasse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClasseMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableClasse);
        if (jTableClasse.getColumnModel().getColumnCount() > 0) {
            jTableClasse.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTableClasse.getColumnModel().getColumn(1).setPreferredWidth(60);
            jTableClasse.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTableClasse.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTableClasse.getColumnModel().getColumn(4).setPreferredWidth(50);
            jTableClasse.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTableClasse.getColumnModel().getColumn(6).setPreferredWidth(50);
            jTableClasse.getColumnModel().getColumn(7).setPreferredWidth(80);
            jTableClasse.getColumnModel().getColumn(8).setPreferredWidth(80);
        }

        jPanelClasse.add(jScrollPane2);
        jScrollPane2.setBounds(10, 130, 840, 290);

        jButtonConsultarClasseAno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/consultar16.png"))); // NOI18N
        jButtonConsultarClasseAno.setToolTipText("");
        jButtonConsultarClasseAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarClasseAnoActionPerformed(evt);
            }
        });
        jPanelClasse.add(jButtonConsultarClasseAno);
        jButtonConsultarClasseAno.setBounds(230, 30, 30, 28);

        jTabbedPane1.addTab("Classe:", jPanelClasse);

        jPanelGradeCurricular.setLayout(null);

        jLabel11.setText("Disciplina:");
        jPanelGradeCurricular.add(jLabel11);
        jLabel11.setBounds(40, 30, 90, 18);

        jComboBoxDisciplina.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxDisciplina.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MATEMATICA", "LINGUA PORTUGUES", "CIENCIAS", "INGLES", "HISTORIA", "GEOGRAFIA", "INFORMATICA" }));
        jPanelGradeCurricular.add(jComboBoxDisciplina);
        jComboBoxDisciplina.setBounds(40, 50, 250, 28);

        jLabel12.setText("Carga Horária:");
        jPanelGradeCurricular.add(jLabel12);
        jLabel12.setBounds(350, 30, 110, 18);

        jLabel13.setText("UF:");
        jPanelGradeCurricular.add(jLabel13);
        jLabel13.setBounds(20, 180, 50, 18);

        jComboBoxProfessorUF.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelGradeCurricular.add(jComboBoxProfessorUF);
        jComboBoxProfessorUF.setBounds(20, 200, 60, 28);

        jLabel14.setText("RG:");
        jPanelGradeCurricular.add(jLabel14);
        jLabel14.setBounds(80, 180, 60, 18);

        jTextFieldProfessorRG.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTextFieldProfessorRG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldProfessorRGKeyPressed(evt);
            }
        });
        jPanelGradeCurricular.add(jTextFieldProfessorRG);
        jTextFieldProfessorRG.setBounds(80, 200, 130, 28);

        jLabel15.setText("Docente:");
        jPanelGradeCurricular.add(jLabel15);
        jLabel15.setBounds(210, 180, 130, 18);

        jTextFieldProfessorNome.setEditable(false);
        jTextFieldProfessorNome.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelGradeCurricular.add(jTextFieldProfessorNome);
        jTextFieldProfessorNome.setBounds(210, 200, 430, 28);

        jTextFieldCargaHoraria.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTextFieldCargaHoraria.setToolTipText("Carga Horária Semanal");
        jPanelGradeCurricular.add(jTextFieldCargaHoraria);
        jTextFieldCargaHoraria.setBounds(350, 50, 130, 28);

        jTabbedPane1.addTab("Grade Curricular:", jPanelGradeCurricular);

        jPanelAlunoClasse.setLayout(null);

        jLabel16.setText("UF:");
        jPanelAlunoClasse.add(jLabel16);
        jLabel16.setBounds(20, 10, 51, 18);

        jComboBoxUF.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelAlunoClasse.add(jComboBoxUF);
        jComboBoxUF.setBounds(20, 30, 60, 28);

        jLabel17.setText("RA:");
        jPanelAlunoClasse.add(jLabel17);
        jLabel17.setBounds(90, 10, 60, 18);

        jTextFieldRA.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTextFieldRA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRAKeyPressed(evt);
            }
        });
        jPanelAlunoClasse.add(jTextFieldRA);
        jTextFieldRA.setBounds(90, 30, 170, 28);

        jLabel18.setText("Nome Completo:");
        jPanelAlunoClasse.add(jLabel18);
        jLabel18.setBounds(270, 10, 140, 18);

        jTextFieldNomeCompleto.setEditable(false);
        jTextFieldNomeCompleto.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelAlunoClasse.add(jTextFieldNomeCompleto);
        jTextFieldNomeCompleto.setBounds(270, 30, 580, 28);

        jLabel19.setText("N°:");
        jPanelAlunoClasse.add(jLabel19);
        jLabel19.setBounds(20, 60, 40, 18);

        jComboBoxSituacao.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelAlunoClasse.add(jComboBoxSituacao);
        jComboBoxSituacao.setBounds(440, 80, 140, 28);

        jButtonAddSituacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanelAlunoClasse.add(jButtonAddSituacao);
        jButtonAddSituacao.setBounds(580, 80, 30, 28);

        jLabel20.setText("Situação:");
        jPanelAlunoClasse.add(jLabel20);
        jLabel20.setBounds(440, 60, 80, 18);

        jLabel21.setText("Deferido:");
        jPanelAlunoClasse.add(jLabel21);
        jLabel21.setBounds(620, 60, 90, 18);

        jComboBoxDef.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxDef.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "SIM", "NÃO" }));
        jPanelAlunoClasse.add(jComboBoxDef);
        jComboBoxDef.setBounds(620, 80, 72, 28);

        jTextFieldObs.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelAlunoClasse.add(jTextFieldObs);
        jTextFieldObs.setBounds(700, 80, 150, 28);

        jLabel22.setText("Obs:");
        jPanelAlunoClasse.add(jLabel22);
        jLabel22.setBounds(700, 60, 57, 18);

        jTableAlunonaClasse.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTableAlunonaClasse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°:", "UF:", "RA:", "Nome:", "D.N:", "Sexo:", "Transf:", "Remanejado:", "Obs:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAlunonaClasse.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTableAlunonaClasse);
        if (jTableAlunonaClasse.getColumnModel().getColumnCount() > 0) {
            jTableAlunonaClasse.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableAlunonaClasse.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTableAlunonaClasse.getColumnModel().getColumn(2).setPreferredWidth(130);
            jTableAlunonaClasse.getColumnModel().getColumn(3).setPreferredWidth(400);
            jTableAlunonaClasse.getColumnModel().getColumn(4).setPreferredWidth(120);
            jTableAlunonaClasse.getColumnModel().getColumn(5).setPreferredWidth(50);
            jTableAlunonaClasse.getColumnModel().getColumn(6).setPreferredWidth(100);
            jTableAlunonaClasse.getColumnModel().getColumn(7).setPreferredWidth(100);
            jTableAlunonaClasse.getColumnModel().getColumn(8).setPreferredWidth(300);
        }

        jPanelAlunoClasse.add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 840, 310);

        jLabel23.setText("Transf:");
        jPanelAlunoClasse.add(jLabel23);
        jLabel23.setBounds(120, 60, 70, 18);

        jTextFieldTransf.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelAlunoClasse.add(jTextFieldTransf);
        jTextFieldTransf.setBounds(120, 80, 150, 28);

        jLabel24.setText("Rem:");
        jPanelAlunoClasse.add(jLabel24);
        jLabel24.setBounds(280, 60, 57, 18);

        jTextFieldRem.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelAlunoClasse.add(jTextFieldRem);
        jTextFieldRem.setBounds(280, 80, 150, 28);

        jComboBoxNChamada.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxNChamada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40" }));
        jPanelAlunoClasse.add(jComboBoxNChamada);
        jComboBoxNChamada.setBounds(20, 80, 90, 28);

        jTabbedPane1.addTab("Alunos na Classe:", jPanelAlunoClasse);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 80, 870, 480);

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/48x48/Consultar48.png"))); // NOI18N
        jButtonPesquisar.setToolTipText("Pesquisar Classe");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(80, 0, 80, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Iniciar(){
       this.setSize(900, 600);
       this.setTitle("Cadastrar - Classe");
       ConsultarAnoLetivo();
       ConsultarEnsino();
       ConsultarSerie();
       ConsultarPeriodo();
       ConsultarTurma();
       ConsultarSala();
       ConsultarUF();
       jTextFieldHorarioFim.setText("11:40");
       jTextFieldHorarioInicio.setText("07:10");
       MostrarDadosClasse();
    }
    
    public void Sair(){
        this.dispose();
    }
    
    public void InserirAnoLetivo(){
    try{
            BaseCTR inserirCTR = new BaseCTR();
            String ano = JOptionPane.showInputDialog("Informe o Ano Letivo:","");
            if ("".equals(ano)){
                JOptionPane.showMessageDialog(null,"Campo em Branco. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                inserirCTR.InserirAnoLetivo(Integer.parseInt(ano));
		JOptionPane.showMessageDialog(null,""+ano+" Inserido com Sucesso. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
                ConsultarAnoLetivo();
            }
	}
            catch(Exception e){
		System.out.println(e.getMessage());
	}    
    }
    
    public void InserirEnsino(){
        try{
            BaseCTR inserirCTR = new BaseCTR();
            String ensino = JOptionPane.showInputDialog("Informe o Tipo de Ensino:","");
            if ("".equals(ensino)){
                JOptionPane.showMessageDialog(null,"Campo em Branco. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                inserirCTR.InserirEnsino(ensino.toUpperCase());
		JOptionPane.showMessageDialog(null,""+ensino+" Inserido com Sucesso. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
                ConsultarEnsino();
            }
	}
            catch(Exception e){
		System.out.println(e.getMessage());
	}    
    }
    
    public void InserirSerie(){
        try{
            BaseCTR inserirCTR = new BaseCTR();
            String serie = JOptionPane.showInputDialog("Informe a Série do Ensino:","");
            if ("".equals(serie)){
                JOptionPane.showMessageDialog(null,"Campo em Branco. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                inserirCTR.InserirSerie(jComboBoxTipoEnsino.getSelectedItem().toString(), serie.toUpperCase());
		JOptionPane.showMessageDialog(null,""+serie+" Inserido com Sucesso. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
                ConsultarSerie();
            }
	}
            catch(Exception e){
		System.out.println(e.getMessage());
	}    
    }
    
    public void ConsultarSerie(){
        try{
            BaseCTR consultarCTR = new BaseCTR();
            ResultSet rs=null;
            rs=consultarCTR.ConsultarSerie(jComboBoxTipoEnsino.getSelectedItem().toString());
            jComboBoxSerie.removeAllItems();
            while(rs.next()){       
                jComboBoxSerie.addItem(rs.getString("ensino_serie_nome"));    
            }
         }
         catch (Exception e){
            System.out.println(e.getMessage());    
           }    
    }
    
    public void ConsultarEnsino(){
        try{
            BaseCTR consultarCTR = new BaseCTR();
            ResultSet rs=null;
            rs=consultarCTR.ConsultarEnsino();
            jComboBoxTipoEnsino.removeAllItems();
            while(rs.next()){       
                jComboBoxTipoEnsino.addItem(rs.getString("ensino_nome"));    
            }
         }
         catch (Exception e){
            System.out.println(e.getMessage());    
           }    
    }
    
    public void ConsultarAnoLetivo(){
        try{
            BaseCTR consultarCTR = new BaseCTR();
            ResultSet rs=null;
            rs=consultarCTR.ConsultarAnoLetivo();
            jComboBoxAnoLetivo.removeAllItems();
            while(rs.next()){       
                jComboBoxAnoLetivo.addItem(rs.getInt("ano_letivo_ano"));    
            }
         }
         catch (Exception e){
            System.out.println(e.getMessage());    
           }   
    }
    
     public void InserirPeriodo(){
        try{
            BaseCTR inserirCTR = new BaseCTR();
            String periodo = JOptionPane.showInputDialog("Informe o Período:","");
            if ("".equals(periodo)){
                JOptionPane.showMessageDialog(null,"Campo em Branco. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                inserirCTR.InserirPeriodo(periodo.toUpperCase());
		JOptionPane.showMessageDialog(null,""+periodo+" Inserido com Sucesso. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
                ConsultarPeriodo();
            }
	}
            catch(Exception e){
		System.out.println(e.getMessage());
	}    
    }
     
     public void ConsultarPeriodo(){
        try{
            BaseCTR consultarCTR = new BaseCTR();
            ResultSet rs=null;
            rs=consultarCTR.ConsultarPeriodo();
            jComboBoxPeriodo.removeAllItems();
            while(rs.next()){       
                jComboBoxPeriodo.addItem(rs.getString("periodo_nome"));    
            }
         }
         catch (Exception e){
            System.out.println(e.getMessage());    
           }    
    }
     
     public void InserirTurma(){
        try{
            BaseCTR inserirCTR = new BaseCTR();
            String turma = JOptionPane.showInputDialog("Informe a Turma:","");
            if ("".equals(turma)){
                JOptionPane.showMessageDialog(null,"Campo em Branco. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                inserirCTR.InserirTurma(Integer.parseInt(jComboBoxAnoLetivo.getSelectedItem().toString()), jComboBoxPeriodo.getSelectedItem().toString(), jComboBoxTipoEnsino.getSelectedItem().toString(), jComboBoxSerie.getSelectedItem().toString(),  turma.toUpperCase());
		JOptionPane.showMessageDialog(null,""+turma+" Inserido com Sucesso. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
                ConsultarTurma();
            }
	}
            catch(Exception e){
		System.out.println(e.getMessage());
	}    
    }
    
    public void ConsultarTurma(){
        try{
            BaseCTR consultarCTR = new BaseCTR();
            ResultSet rs=null;
            rs=consultarCTR.ConsultarTurma(Integer.parseInt(jComboBoxAnoLetivo.getSelectedItem().toString()), jComboBoxPeriodo.getSelectedItem().toString(), jComboBoxTipoEnsino.getSelectedItem().toString(), jComboBoxSerie.getSelectedItem().toString());
            jComboBoxTurma.removeAllItems();
            while(rs.next()){       
                jComboBoxTurma.addItem(rs.getString("turma_nome"));    
            }
         }
         catch (Exception e){
            System.out.println(e.getMessage());    
           }    
    }
    
    public void InserirSala(){
        try{
            BaseCTR inserirCTR = new BaseCTR();
            String sala = JOptionPane.showInputDialog("Informe a Sala:","");
            if ("".equals(sala)){
                JOptionPane.showMessageDialog(null,"Campo em Branco. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                inserirCTR.InserirEmpresaSala(sala);
		JOptionPane.showMessageDialog(null,""+sala+" Inserido com Sucesso. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
                ConsultarSala();
            }
	}
            catch(Exception e){
		System.out.println(e.getMessage());
	}    
    }
    
    public void ConsultarSala(){
        try{
            BaseCTR consultarCTR = new BaseCTR();
            ResultSet rs=null;
            rs=consultarCTR.ConsultarEmpresaSala();
            jComboBoxSala.removeAllItems();
            while(rs.next()){       
                jComboBoxSala.addItem(rs.getString("empresa_sala_numero"));    
            }
         }
         catch (Exception e){
            System.out.println(e.getMessage());    
           }    
    }
    
    
    public void MododeGravacao(){
       if(jPanelClasse.isVisible()){
           VerificarClasse();
       }
       if(jPanelGradeCurricular.isVisible()){
          JOptionPane.showMessageDialog(null,"Grade Curricular","Informação: ",JOptionPane.INFORMATION_MESSAGE); 
       }
       if(jPanelAlunoClasse.isVisible()){
          InserirAlunoClasse();
       }
    }
    
    public void ConsultarClasse(){
        System.out.println("em contrução");
        //JOptionPane.showMessageDialog(null,"Em Contrução...","Informação: ",JOptionPane.INFORMATION_MESSAGE); 
    }
    
    public void VerificarClasse(){
    try{
            BaseCTR consultarCTR = new BaseCTR();
            ResultSet rs=null;
            rs=consultarCTR.VerificarClasse(jTextFieldClasseNumero.getText().toUpperCase().replace(".", "").replace("-", ""));
            int v = 0;
            while(rs.next()){       
                v = (rs.getInt("verificador"));  
            }
            if (v == 0){
                InserirClasse();
            }else{
                AlterarClasse();
            }
         }
         catch (Exception e){
            System.out.println(e.getMessage());    
            }    
    }
    
    public void InserirAlunoClasse(){
    try{
            BaseCTR inserirCTR = new BaseCTR();
            if ("".equals(jTextFieldClasseNumero.getText())|| "".equals(jComboBoxUF.getSelectedItem()) || "".equals(jTextFieldRA.getText()) || "".equals(jTextFieldNomeCompleto.getText()) || "".equals(jComboBoxNChamada.getSelectedItem())){
               JOptionPane.showMessageDialog(null,"Campos de Dados em Branco, Verifique...","Informação: ",JOptionPane.INFORMATION_MESSAGE);   
               jTextFieldRA.requestFocus();
            }else{
                int i = JOptionPane.showConfirmDialog(null, "Deseja Inserir este Aluno nesta Classe? ","Informação: ", JOptionPane.YES_NO_OPTION);
                if(i == JOptionPane.YES_OPTION){
                    inserirCTR.InserirAlunoClasse(jTextFieldClasseNumero.getText().toUpperCase().replace(".", "").replace("-", ""), jComboBoxUF.getSelectedItem().toString(),jTextFieldRA.getText().toUpperCase().replace(".", "").replace("-", ""), Integer.parseInt((String) jComboBoxNChamada.getSelectedItem()), jTextFieldTransf.getText().toUpperCase(), jTextFieldRem.getText().toUpperCase(), (String)jComboBoxSituacao.getSelectedItem(), (String)jComboBoxDef.getSelectedItem(), jTextFieldObs.getText().toUpperCase());
                    JOptionPane.showMessageDialog(null,"Aluno(a) Inserido(a) com Sucesso. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
                    LimparCamposAluno();
                    MostrarAlunosClasse();
                }
                }
            }
            catch(HeadlessException | NumberFormatException e){
                //JOptionPane.showMessageDialog(null,"Campos de Dados em Branco... ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
		System.out.println(e.getMessage());
	}    
    }
    
    public void InserirClasse(){
    try{
            BaseCTR inserirCTR = new BaseCTR();	
            if ("".equals(jTextFieldClasseNumero.getText()) || "".equals(jComboBoxAnoLetivo.getSelectedItem()) || "".equals(jComboBoxTipoEnsino.getSelectedItem()) || "".equals(jComboBoxSerie.getSelectedItem()) || "".equals(jComboBoxSala.getSelectedItem()) || "".equals(jComboBoxPeriodo.getSelectedItem()) || "".equals(jComboBoxTurma.getSelectedItem())){
               JOptionPane.showMessageDialog(null,"Campos de Dados em Branco, Verifique...","Informação: ",JOptionPane.INFORMATION_MESSAGE);   
               jTextFieldClasseNumero.requestFocus();
            }else{
                int i = JOptionPane.showConfirmDialog(null, "Deseja Inserir esta Classe? ","Informação: ", JOptionPane.YES_NO_OPTION);
                if(i == JOptionPane.YES_OPTION){
                    inserirCTR.InserirClasse(jTextFieldClasseNumero.getText().toUpperCase().replace(".", "").replace("-", "").replace(" ",""), jComboBoxTipoEnsino.getSelectedItem().toString(), jComboBoxSerie.getSelectedItem().toString(), jComboBoxTurma.getSelectedItem().toString(), jComboBoxPeriodo.getSelectedItem().toString(), Integer.parseInt(jComboBoxAnoLetivo.getSelectedItem().toString()), jComboBoxSala.getSelectedItem().toString(), jTextFieldHorarioInicio.getText(), jTextFieldHorarioFim.getText(), jTextFieldClasseObs.getText().toUpperCase());
                    JOptionPane.showMessageDialog(null,"Classe Inserida com Sucesso. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
                    LimparCampos();
                    MostrarDadosClasse();
                }
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Campos de Dados em Branco... ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
		System.out.println(e.getMessage());
	}    
    }
    
    public void AlterarClasse(){
        try{
            BaseCTR alterarCTR = new BaseCTR();	
            if ("".equals(jTextFieldClasseNumero.getText()) || "".equals(jComboBoxAnoLetivo.getSelectedItem()) || "".equals(jComboBoxTipoEnsino.getSelectedItem()) || "".equals(jComboBoxSerie.getSelectedItem()) || "".equals(jComboBoxSala.getSelectedItem()) || "".equals(jComboBoxPeriodo.getSelectedItem()) || "".equals(jComboBoxTurma.getSelectedItem())){
               JOptionPane.showMessageDialog(null,"Campos de Dados em Branco, Verifique...","Informação: ",JOptionPane.INFORMATION_MESSAGE);   
               jTextFieldClasseNumero.requestFocus();
            }else{
                int i = JOptionPane.showConfirmDialog(null, "Deseja Alterar esta Classe? ","Informação: ", JOptionPane.YES_NO_OPTION);
                if(i == JOptionPane.YES_OPTION){
                    alterarCTR.AlterarClasse(jTextFieldClasseNumero.getText().toUpperCase().replace(".", "").replace("-", "").replace(" ",""), jComboBoxTipoEnsino.getSelectedItem().toString(), jComboBoxSerie.getSelectedItem().toString(), jComboBoxTurma.getSelectedItem().toString(), jComboBoxPeriodo.getSelectedItem().toString(), Integer.parseInt(jComboBoxAnoLetivo.getSelectedItem().toString()), jComboBoxSala.getSelectedItem().toString(), jTextFieldHorarioInicio.getText(), jTextFieldHorarioFim.getText(), jTextFieldClasseObs.getText().toUpperCase());
                    JOptionPane.showMessageDialog(null,"Classe Alterada com Sucesso. ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
                    LimparCampos();
                    MostrarDadosClasse();
                }
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Campos de Dados em Branco... ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
		System.out.println(e.getMessage());
	}
    }
    
    public void LimparCamposAluno(){
        jComboBoxUF.setSelectedItem("SP");
        jTextFieldRA.setText("");
        jTextFieldNomeCompleto.setText("");
        jTextFieldObs.setText("");
    }
    
    public void LimparCampos(){
        //jTextFieldClasseNumero.setText("");
        jTextFieldClasseObs.setText("");
        jTextFieldHorarioFim.setText("11:40");
        jTextFieldHorarioInicio.setText("07:10");
        //jTextFieldRA.setText("");
    }
    
    public void MostrarDadosClasse(){
        try{
            BaseCTR consultarCTR = new BaseCTR();
            ResultSet rs=null;
            rs=consultarCTR.MostrarDadosClasse(Integer.parseInt(jComboBoxAnoLetivo.getSelectedItem().toString()));
            DefaultTableModel modelo = (DefaultTableModel) jTableClasse.getModel();
            modelo.setNumRows(0);
            while (rs.next()){
                Object[] novaLinha = new Object[9];
                novaLinha[0] = rs.getString("classe_numero");
                novaLinha[1] = rs.getString("ano_letivo_ano");
                novaLinha[2] = rs.getString("ensino_nome");
                novaLinha[3] = rs.getString("ensino_serie");
                novaLinha[4] = rs.getString("turma_nome");
                novaLinha[5] = rs.getString("periodo_nome");
                novaLinha[6] = rs.getString("empresa_sala_numero");
                novaLinha[7] = rs.getString("classe_hinicial");
                novaLinha[8] = rs.getString("classe_hfinal");
                modelo.addRow(novaLinha);
            }
        }
        catch (Exception e){
            System.out.println(e.getMessage());    
           }
    }
    
    public void MostrarAlunosClasse(){
        try{
            BaseCTR consultarCTR = new BaseCTR();
            ResultSet rs=null;
            rs=consultarCTR.MostrarAlunosClasse(jTextFieldClasseNumero.getText());
            DefaultTableModel modelo = (DefaultTableModel) jTableAlunonaClasse.getModel();
            modelo.setNumRows(0);
            while (rs.next()){
                Object[] novaLinha = new Object[9];
                novaLinha[0] = rs.getString("aluno_classe_nchamada");
                novaLinha[1] = rs.getString("pessoa_ci_uf");
                novaLinha[2] = rs.getString("pessoa_ci_numero");
                novaLinha[3] = rs.getString("pessoa_nome");
                novaLinha[4] = rs.getString("pessoa_dn");
                novaLinha[5] = rs.getString("pessoa_sexo");
                novaLinha[6] = rs.getString("aluno_classe_tranf");
                novaLinha[7] = rs.getString("aluno_classe_rem");
                novaLinha[8] = rs.getString("aluno_classe_obs");
                modelo.addRow(novaLinha);
            }
        }
        catch (Exception e){
            System.out.println(e.getMessage());    
           }
    }
    
    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        MododeGravacao();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        Sair();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonAddAnoLetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddAnoLetivoActionPerformed
        // TODO add your handling code here:
        InserirAnoLetivo();
    }//GEN-LAST:event_jButtonAddAnoLetivoActionPerformed

    private void jButtonAddTipoEnsinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTipoEnsinoActionPerformed
        // TODO add your handling code here:
        InserirEnsino();
    }//GEN-LAST:event_jButtonAddTipoEnsinoActionPerformed

    private void jButtonConsultarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarSerieActionPerformed
        // TODO add your handling code here:
        ConsultarSerie();
    }//GEN-LAST:event_jButtonConsultarSerieActionPerformed

    private void jButtonAddSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSerieActionPerformed
        // TODO add your handling code here:
        InserirSerie();
    }//GEN-LAST:event_jButtonAddSerieActionPerformed

    private void jButtonAddSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSalaActionPerformed
        // TODO add your handling code here:
        InserirSala();
    }//GEN-LAST:event_jButtonAddSalaActionPerformed

    private void jButtonAddPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPeriodoActionPerformed
        // TODO add your handling code here:
        InserirPeriodo();
    }//GEN-LAST:event_jButtonAddPeriodoActionPerformed

    private void jButtonConsultarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarTurmaActionPerformed
        // TODO add your handling code here:
        ConsultarTurma();
    }//GEN-LAST:event_jButtonConsultarTurmaActionPerformed

    private void jButtonAddTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTurmaActionPerformed
        // TODO add your handling code here:
        InserirTurma();
    }//GEN-LAST:event_jButtonAddTurmaActionPerformed

    
    private void jTextFieldClasseNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldClasseNumeroKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == evt.VK_ENTER){
            LimparCampos();
            MostrarAlunosClasse();
            MostrarDadosClasse();
            ConsultarClasse();
        }
    }//GEN-LAST:event_jTextFieldClasseNumeroKeyPressed

    private void jButtonConsultarClasseAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarClasseAnoActionPerformed
        // TODO add your handling code here:
        MostrarDadosClasse();
    }//GEN-LAST:event_jButtonConsultarClasseAnoActionPerformed

    private void jTextFieldProfessorRGKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProfessorRGKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER){

        }
    }//GEN-LAST:event_jTextFieldProfessorRGKeyPressed

    private void jTableClasseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClasseMouseClicked
        // TODO add your handling code here:
        int linha = jTableClasse.getSelectedRow();
        jTextFieldClasseNumero.setText(jTableClasse.getValueAt(linha,0).toString());
        jComboBoxAnoLetivo.setSelectedItem(jTableClasse.getValueAt(linha,1).toString());
        jComboBoxTipoEnsino.setSelectedItem(jTableClasse.getValueAt(linha,2).toString());
        jComboBoxSerie.setSelectedItem(jTableClasse.getValueAt(linha,3).toString());
        jComboBoxTurma.setSelectedItem(jTableClasse.getValueAt(linha,4).toString());
        jComboBoxPeriodo.setSelectedItem(jTableClasse.getValueAt(linha,5).toString());
        jComboBoxSala.setSelectedItem(jTableClasse.getValueAt(linha,6).toString());
        jTextFieldHorarioInicio.setText(jTableClasse.getValueAt(linha,7).toString());
        jTextFieldHorarioFim.setText(jTableClasse.getValueAt(linha,8).toString());
    }//GEN-LAST:event_jTableClasseMouseClicked

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:
        ClasseConsultaDIALOG  jDialog = new ClasseConsultaDIALOG(null, true);
        jDialog.setModal(true);
        jDialog.setVisible(true);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTextFieldRAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRAKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER){
            AlunoConsultaDIALOG  jDialog = new AlunoConsultaDIALOG(null, true);
            jDialog.setModal(true);
            jDialog.setVisible(true);
            jComboBoxUF.setSelectedItem(jDialog.getGetuf());
            jTextFieldRA.setText(jDialog.getGetid());
            jTextFieldNomeCompleto.setText(jDialog.getGetnome());
            jTextFieldRA.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldRAKeyPressed

    public void ConsultarUF(){
        try{
            BaseCTR consultarCTR = new BaseCTR();
            ResultSet rs=null;
            rs=consultarCTR.ConsultarUF();
            jComboBoxUF.removeAllItems();
            jComboBoxProfessorUF.removeAllItems();
            //jComboBoxUFEnd.removeAllItems();
            while(rs.next()){       
                jComboBoxUF.addItem(rs.getString("uf_nome"));    
                jComboBoxProfessorUF.addItem(rs.getString("uf_nome"));
            }
         }
         catch (Exception e){
            System.out.println(e.getMessage());    
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddAnoLetivo;
    private javax.swing.JButton jButtonAddPeriodo;
    private javax.swing.JButton jButtonAddSala;
    private javax.swing.JButton jButtonAddSerie;
    private javax.swing.JButton jButtonAddSituacao;
    private javax.swing.JButton jButtonAddTipoEnsino;
    private javax.swing.JButton jButtonAddTurma;
    private javax.swing.JButton jButtonConsultarClasseAno;
    private javax.swing.JButton jButtonConsultarSerie;
    private javax.swing.JButton jButtonConsultarTurma;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxAnoLetivo;
    private javax.swing.JComboBox jComboBoxDef;
    private javax.swing.JComboBox jComboBoxDisciplina;
    private javax.swing.JComboBox jComboBoxNChamada;
    private javax.swing.JComboBox jComboBoxPeriodo;
    private javax.swing.JComboBox jComboBoxProfessorUF;
    private javax.swing.JComboBox jComboBoxSala;
    private javax.swing.JComboBox jComboBoxSerie;
    private javax.swing.JComboBox jComboBoxSituacao;
    private javax.swing.JComboBox jComboBoxTipoEnsino;
    private javax.swing.JComboBox jComboBoxTurma;
    private javax.swing.JComboBox jComboBoxUF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelAlunoClasse;
    private javax.swing.JPanel jPanelClasse;
    private javax.swing.JPanel jPanelGradeCurricular;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableAlunonaClasse;
    private javax.swing.JTable jTableClasse;
    private javax.swing.JTextField jTextFieldCargaHoraria;
    private javax.swing.JTextField jTextFieldClasseNumero;
    private javax.swing.JTextField jTextFieldClasseObs;
    private javax.swing.JTextField jTextFieldHorarioFim;
    private javax.swing.JTextField jTextFieldHorarioInicio;
    private javax.swing.JTextField jTextFieldNomeCompleto;
    private javax.swing.JTextField jTextFieldObs;
    private javax.swing.JTextField jTextFieldProfessorNome;
    private javax.swing.JTextField jTextFieldProfessorRG;
    private javax.swing.JTextField jTextFieldRA;
    private javax.swing.JTextField jTextFieldRem;
    private javax.swing.JTextField jTextFieldTransf;
    // End of variables declaration//GEN-END:variables
}
