/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.escola;

import base.ctr.BaseCTR;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Douglas Estanislau Pereira
 */
public class ClasseConsultaDIALOG extends javax.swing.JDialog {

    private String cod, ano, ensino, serie, turma, periodo, sala, horai, horaf;
    
    /**
     * Creates new form ClasseConsultaDIALOG
     */
    public ClasseConsultaDIALOG(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jComboBoxAnoLetivo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButtonPesquisaClasse = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableClasse = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Pesquisar por:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 10, 120, 18);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/48x48/Sair48.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(0, 0, 80, 80);

        jComboBoxAnoLetivo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        getContentPane().add(jComboBoxAnoLetivo);
        jComboBoxAnoLetivo.setBounds(100, 70, 80, 28);

        jLabel2.setText("Ano Letivo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 50, 90, 18);

        jButtonPesquisaClasse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/consultar16.png"))); // NOI18N
        jButtonPesquisaClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaClasseActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisaClasse);
        jButtonPesquisaClasse.setBounds(180, 70, 30, 28);

        jTableClasse.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTableClasse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número:", "Ano Letivo:", "Tipo de Ensino:", "Série:", "Turma:", "Período:", "Sala:", "H. Início:", "H. Fim:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClasse.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableClasse.getTableHeader().setReorderingAllowed(false);
        jTableClasse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClasseMouseClicked(evt);
            }
        });
        jTableClasse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableClasseKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableClasse);
        if (jTableClasse.getColumnModel().getColumnCount() > 0) {
            jTableClasse.getColumnModel().getColumn(0).setPreferredWidth(120);
            jTableClasse.getColumnModel().getColumn(1).setPreferredWidth(70);
            jTableClasse.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTableClasse.getColumnModel().getColumn(3).setPreferredWidth(70);
            jTableClasse.getColumnModel().getColumn(4).setPreferredWidth(70);
            jTableClasse.getColumnModel().getColumn(5).setPreferredWidth(150);
            jTableClasse.getColumnModel().getColumn(6).setPreferredWidth(50);
            jTableClasse.getColumnModel().getColumn(7).setPreferredWidth(100);
            jTableClasse.getColumnModel().getColumn(8).setPreferredWidth(100);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 110, 830, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Iniciar(){
       this.setSize(850, 375);
       this.setTitle("Consultar - Classe");
       ConsultarAnoLetivo();
       MostrarDadosClasse();
    }
    
    public void MostrarDadosClasse(){
        try{
            BaseCTR consultarCTR = new BaseCTR();
            ResultSet rs=null;
            rs=consultarCTR.MostrarDadosClasse(Integer.parseInt(jComboBoxAnoLetivo.getSelectedItem().toString()));
            DefaultTableModel modelo = (DefaultTableModel) jTableClasse.getModel();
            modelo.setNumRows(0);
            while (rs.next()){
                Object[] novaLinha = new Object[9];
                novaLinha[0] = rs.getString("classe_numero");
                novaLinha[1] = rs.getString("ano_letivo_ano");
                novaLinha[2] = rs.getString("ensino_nome");
                novaLinha[3] = rs.getString("ensino_serie");
                novaLinha[4] = rs.getString("turma_nome");
                novaLinha[5] = rs.getString("periodo_nome");
                novaLinha[6] = rs.getString("empresa_sala_numero");
                novaLinha[7] = rs.getString("classe_hinicial");
                novaLinha[8] = rs.getString("classe_hfinal");
                modelo.addRow(novaLinha);
            }
        }
        catch (Exception e){
            System.out.println(e.getMessage());    
           }
    }
    
    public void ConsultarAnoLetivo(){
        try{
            BaseCTR consultarCTR = new BaseCTR();
            ResultSet rs=null;
            rs=consultarCTR.ConsultarAnoLetivo();
            jComboBoxAnoLetivo.removeAllItems();
            while(rs.next()){       
                jComboBoxAnoLetivo.addItem(rs.getInt("ano_letivo_ano"));    
            }
         }
         catch (Exception e){
            System.out.println(e.getMessage());    
           }   
    }
    
    public void ChaveSelecao(){
        int linha = jTableClasse.getSelectedRow();
        setCod(jTableClasse.getValueAt(linha,0).toString());
        setAno(jTableClasse.getValueAt(linha,1).toString());
        setEnsino(jTableClasse.getValueAt(linha,2).toString());
        setSerie(jTableClasse.getValueAt(linha,3).toString());
        setTurma(jTableClasse.getValueAt(linha,4).toString());
        setPeriodo(jTableClasse.getValueAt(linha,5).toString());
        setSala(jTableClasse.getValueAt(linha,6).toString());
        setHorai(jTableClasse.getValueAt(linha,7).toString());
        setHoraf(jTableClasse.getValueAt(linha,8).toString());
        this.dispose();
    }
    
    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        Sair();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonPesquisaClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaClasseActionPerformed
        // TODO add your handling code here:
        MostrarDadosClasse();
    }//GEN-LAST:event_jButtonPesquisaClasseActionPerformed

    private void jTableClasseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClasseMouseClicked
        // TODO add your handling code here:
        ChaveSelecao();
    }//GEN-LAST:event_jTableClasseMouseClicked

    private void jTableClasseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableClasseKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER){
            ChaveSelecao();
        }
    }//GEN-LAST:event_jTableClasseKeyPressed

    public void Sair(){
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClasseConsultaDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClasseConsultaDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClasseConsultaDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClasseConsultaDIALOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ClasseConsultaDIALOG dialog = new ClasseConsultaDIALOG(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPesquisaClasse;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox jComboBoxAnoLetivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableClasse;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the cod
     */
    public String getCod() {
        return cod;
    }

    /**
     * @param cod the cod to set
     */
    public void setCod(String cod) {
        this.cod = cod;
    }

    /**
     * @return the ano
     */
    public String getAno() {
        return ano;
    }

    /**
     * @param ano the ano to set
     */
    public void setAno(String ano) {
        this.ano = ano;
    }

    /**
     * @return the ensino
     */
    public String getEnsino() {
        return ensino;
    }

    /**
     * @param ensino the ensino to set
     */
    public void setEnsino(String ensino) {
        this.ensino = ensino;
    }

    /**
     * @return the serie
     */
    public String getSerie() {
        return serie;
    }

    /**
     * @param serie the serie to set
     */
    public void setSerie(String serie) {
        this.serie = serie;
    }

    /**
     * @return the turma
     */
    public String getTurma() {
        return turma;
    }

    /**
     * @param turma the turma to set
     */
    public void setTurma(String turma) {
        this.turma = turma;
    }

    /**
     * @return the periodo
     */
    public String getPeriodo() {
        return periodo;
    }

    /**
     * @param periodo the periodo to set
     */
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }

    /**
     * @return the sala
     */
    public String getSala() {
        return sala;
    }

    /**
     * @param sala the sala to set
     */
    public void setSala(String sala) {
        this.sala = sala;
    }

    /**
     * @return the horai
     */
    public String getHorai() {
        return horai;
    }

    /**
     * @param horai the horai to set
     */
    public void setHorai(String horai) {
        this.horai = horai;
    }

    /**
     * @return the horaf
     */
    public String getHoraf() {
        return horaf;
    }

    /**
     * @param horaf the horaf to set
     */
    public void setHoraf(String horaf) {
        this.horaf = horaf;
    }
}
