/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.escola;

import base.ctr.BaseCTR;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Douglas Estanislau Pereira
 */
public class PessoaNasMultVIEW extends javax.swing.JInternalFrame {

    /**
     * Creates new form PessoaNasMultVIEW
     */
    public PessoaNasMultVIEW() {
        initComponents();
        Iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPesquisarNM = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jComboBoxNM = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNM = new javax.swing.JTable();
        jTextFieldContador = new javax.swing.JTextField();

        getContentPane().setLayout(null);

        jButtonPesquisarNM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/48x48/Consultar48.png"))); // NOI18N
        jButtonPesquisarNM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarNMActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisarNM);
        jButtonPesquisarNM.setBounds(0, 0, 80, 80);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/48x48/Sair48.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 0, 80, 80);

        jComboBoxNM.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxNM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GEMEOS", "TRIGEMEOS", "QUADRIGEMEOS" }));
        getContentPane().add(jComboBoxNM);
        jComboBoxNM.setBounds(10, 100, 240, 26);

        jTableNM.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTableNM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID:", "Nome:", "D.N:", "Sexo:", "Cargo:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableNM);
        if (jTableNM.getColumnModel().getColumnCount() > 0) {
            jTableNM.getColumnModel().getColumn(0).setMinWidth(40);
            jTableNM.getColumnModel().getColumn(1).setMinWidth(400);
            jTableNM.getColumnModel().getColumn(2).setMinWidth(80);
            jTableNM.getColumnModel().getColumn(3).setMinWidth(40);
            jTableNM.getColumnModel().getColumn(4).setMinWidth(110);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 140, 870, 420);

        jTextFieldContador.setEditable(false);
        jTextFieldContador.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        getContentPane().add(jTextFieldContador);
        jTextFieldContador.setBounds(250, 100, 50, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarNMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarNMActionPerformed
        // TODO add your handling code here:
        MostrarDadosTabelaPessoaNM();
    }//GEN-LAST:event_jButtonPesquisarNMActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Sair();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void Iniciar(){
        this.setTitle("Lista de Pessoas com Nascimento Múltiplos");
        this.setSize(900, 600);
    }

    public void Sair(){
        this.dispose();
    }
    
    public void MostrarDadosTabelaPessoaNM(){
        int n = 0;
        jTextFieldContador.setText("");
        try{
            BaseCTR consultarCTR = new BaseCTR();
            ResultSet rs=null;
            rs=consultarCTR.ConsultarPessoaNM(jComboBoxNM.getSelectedItem().toString());
            DefaultTableModel modelo = (DefaultTableModel) jTableNM.getModel();
            modelo.setNumRows(0);
            while (rs.next()){
                n++;
                Object[] novaLinha = new Object[5];
                novaLinha[0] = rs.getString("pessoa_id");
                novaLinha[1] = rs.getString("pessoa_nome");
                novaLinha[2] = rs.getString("pessoa_dn");
                novaLinha[3] = rs.getString("pessoa_sexo");
                novaLinha[4] = rs.getString("cargo_nome");
                modelo.addRow(novaLinha);
                jTextFieldContador.setText(""+n);
            }
        }
        catch (Exception e){
            System.out.println(e.getMessage());    
            }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonPesquisarNM;
    private javax.swing.JComboBox jComboBoxNM;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNM;
    private javax.swing.JTextField jTextFieldContador;
    // End of variables declaration//GEN-END:variables
}
