/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.escola;

import javax.swing.JOptionPane;

/**
 *
 * @author Douglas Estanislau Pereira
 */
public class ProfessorCadastroVIEW extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProfessorCadastroVIEW
     */
    public ProfessorCadastroVIEW() {
        initComponents();
        Iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGravarAlterar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelCI = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldRIC = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxRGUF = new javax.swing.JComboBox();
        jButtonAddRG = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPrenome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSobrenome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAgnome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNomeCompleto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox();
        jButtonAddSexo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldDN = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxNaturalidadeUF = new javax.swing.JComboBox();
        jComboBoxNaturalidadeCidade = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jButtonAddUF = new javax.swing.JButton();
        jButtonAddCidade = new javax.swing.JButton();
        jButtonConsultarCidade = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxNaturalidadePais = new javax.swing.JComboBox();
        jButtonAddPais = new javax.swing.JButton();
        jButtonConsultarEstado = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxOrgaoEmissor = new javax.swing.JComboBox();
        jButtonAddOrgaoEmissor = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTextFieldDocFolha = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldDocLivro = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldDocNumero = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxDocTipo = new javax.swing.JComboBox();
        jButtonAddCertidao = new javax.swing.JButton();
        jRadioButtonDocAntigo = new javax.swing.JRadioButton();
        jRadioButtonDocNovo = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jComboBoxDocUF = new javax.swing.JComboBox();
        jButtonAddDocUF = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jComboBoxDocCidade = new javax.swing.JComboBox();
        jButtonAddDocCidade = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jButtonAddDocComarca = new javax.swing.JButton();
        jButtonConsultarComarca = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jFormattedTextFieldCIDE = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldFiliacaoPai = new javax.swing.JTextField();
        jTextFieldFiliacaoMae = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCIObs = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jPanelCI2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        jFormattedTextFieldCPFDE = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jFormattedTextFieldTE = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTEDE = new javax.swing.JFormattedTextField();
        jComboBoxTEUF = new javax.swing.JComboBox();
        jButtonAddUF2 = new javax.swing.JButton();
        jComboBoxTEMunicipio = new javax.swing.JComboBox();
        jButtonAddCidade2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jFormattedTextFieldPISPASEP = new javax.swing.JFormattedTextField();
        jFormattedTextFieldPISPASEPDE = new javax.swing.JFormattedTextField();
        jLabel32 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        jFormattedTextFieldCNH = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCNH1Habilitacao = new javax.swing.JFormattedTextField();
        jLabel34 = new javax.swing.JLabel();
        jComboBoxCNHCategoria = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        jButtonAddCNHCategoria = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jFormattedTextFieldCNHValidade = new javax.swing.JFormattedTextField();
        jLabel37 = new javax.swing.JLabel();
        jComboBoxCNHPermissao = new javax.swing.JComboBox();
        jLabel38 = new javax.swing.JLabel();
        jFormattedTextFieldCNHDE = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaCNHObs = new javax.swing.JTextArea();
        jComboBoxCNHUF = new javax.swing.JComboBox();
        jLabel40 = new javax.swing.JLabel();
        jButtonAddUF3 = new javax.swing.JButton();
        jButtonAddCNHPermissao = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButtonAddCNHCidade = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel42 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel39 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jFormattedTextFieldTEZona = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTESecao = new javax.swing.JFormattedTextField();
        jPanelEndereco = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jComboBoxEnderecoPais = new javax.swing.JComboBox();
        jLabel44 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboBoxEnderecoUF = new javax.swing.JComboBox();
        jLabel45 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jComboBoxEnderecoCidade = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jComboBoxEnderecoCEP = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jComboBoxEnderecoZona = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jComboBoxEnderecoBairro = new javax.swing.JComboBox();
        jButton7 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jComboBoxEnderecoLogradouro = new javax.swing.JComboBox();
        jButton8 = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        jTextFieldEnderecoNumero = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jComboBoxEnderecoTipo = new javax.swing.JComboBox();
        jButton9 = new javax.swing.JButton();
        jLabel51 = new javax.swing.JLabel();
        jTextFieldEnderecoComplemento = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableEndereco = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaEnderecoObs = new javax.swing.JTextArea();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jPanelTelefones = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jButton10 = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        getContentPane().setLayout(null);

        jButtonGravarAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/48x48/Gravar48.png"))); // NOI18N
        jButtonGravarAlterar.setToolTipText("Gravar ou Alterar Aluno");
        jButtonGravarAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGravarAlterar);
        jButtonGravarAlterar.setBounds(0, 0, 70, 70);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/48x48/Sair48.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(140, 0, 70, 70);

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/48x48/Consultar48.png"))); // NOI18N
        jButtonPesquisar.setToolTipText("Pesquisar Aluno");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(70, 0, 70, 70);

        jPanelCI.setLayout(null);

        jLabel1.setText("* RG ou RIC:");
        jPanelCI.add(jLabel1);
        jLabel1.setBounds(10, 10, 110, 14);

        jTextFieldRIC.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTextFieldRIC.setToolTipText("Exemplo RG/UF: 12345678-9/SP\nExemplo RIC: 1234567890-9");
        jPanelCI.add(jTextFieldRIC);
        jTextFieldRIC.setBounds(10, 30, 110, 26);

        jLabel12.setText("UF:");
        jPanelCI.add(jLabel12);
        jLabel12.setBounds(120, 10, 40, 14);

        jComboBoxRGUF.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelCI.add(jComboBoxRGUF);
        jComboBoxRGUF.setBounds(120, 30, 70, 26);

        jButtonAddRG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanelCI.add(jButtonAddRG);
        jButtonAddRG.setBounds(190, 30, 30, 28);

        jLabel2.setText("* Prenome:");
        jPanelCI.add(jLabel2);
        jLabel2.setBounds(220, 10, 130, 14);

        jTextFieldPrenome.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTextFieldPrenome.setToolTipText("Exemplo: João Felipe Alves");
        jPanelCI.add(jTextFieldPrenome);
        jTextFieldPrenome.setBounds(220, 30, 330, 26);

        jLabel3.setText("* Sobrenome: ");
        jPanelCI.add(jLabel3);
        jLabel3.setBounds(550, 10, 140, 14);

        jTextFieldSobrenome.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTextFieldSobrenome.setToolTipText("Exemplo: Silva");
        jPanelCI.add(jTextFieldSobrenome);
        jTextFieldSobrenome.setBounds(550, 30, 180, 26);

        jLabel4.setText("Agnome:");
        jPanelCI.add(jLabel4);
        jLabel4.setBounds(730, 10, 80, 14);

        jTextFieldAgnome.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelCI.add(jTextFieldAgnome);
        jTextFieldAgnome.setBounds(730, 30, 140, 26);

        jLabel5.setText("Nome Completo:");
        jPanelCI.add(jLabel5);
        jLabel5.setBounds(440, 70, 140, 14);

        jTextFieldNomeCompleto.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelCI.add(jTextFieldNomeCompleto);
        jTextFieldNomeCompleto.setBounds(440, 90, 430, 26);

        jLabel6.setText("Sexo:");
        jPanelCI.add(jLabel6);
        jLabel6.setBounds(110, 70, 28, 14);

        jComboBoxSexo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "F", "M" }));
        jComboBoxSexo.setToolTipText("Sexo");
        jPanelCI.add(jComboBoxSexo);
        jComboBoxSexo.setBounds(110, 90, 60, 26);

        jButtonAddSexo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanelCI.add(jButtonAddSexo);
        jButtonAddSexo.setBounds(170, 90, 30, 28);

        jLabel7.setText("* Dt.Nasc:");
        jPanelCI.add(jLabel7);
        jLabel7.setBounds(10, 70, 90, 14);

        try {
            jFormattedTextFieldDN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDN.setToolTipText("Data de Nascimento");
        jFormattedTextFieldDN.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelCI.add(jFormattedTextFieldDN);
        jFormattedTextFieldDN.setBounds(10, 90, 100, 26);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Naturalidade:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 12))); // NOI18N
        jPanel4.setLayout(null);

        jLabel8.setText("UF:");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(370, 20, 40, 14);

        jComboBoxNaturalidadeUF.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanel4.add(jComboBoxNaturalidadeUF);
        jComboBoxNaturalidadeUF.setBounds(400, 20, 70, 26);

        jComboBoxNaturalidadeCidade.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanel4.add(jComboBoxNaturalidadeCidade);
        jComboBoxNaturalidadeCidade.setBounds(580, 20, 240, 26);

        jLabel9.setText("Cidade:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(520, 20, 60, 14);

        jButtonAddUF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanel4.add(jButtonAddUF);
        jButtonAddUF.setBounds(470, 20, 30, 28);

        jButtonAddCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanel4.add(jButtonAddCidade);
        jButtonAddCidade.setBounds(820, 20, 30, 28);

        jButtonConsultarCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/consultar16.png"))); // NOI18N
        jPanel4.add(jButtonConsultarCidade);
        jButtonConsultarCidade.setBounds(460, 20, 30, 27);

        jLabel11.setText("País:");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(140, 20, 50, 14);

        jComboBoxNaturalidadePais.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxNaturalidadePais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BRASIL" }));
        jPanel4.add(jComboBoxNaturalidadePais);
        jComboBoxNaturalidadePais.setBounds(190, 20, 130, 26);

        jButtonAddPais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanel4.add(jButtonAddPais);
        jButtonAddPais.setBounds(320, 20, 30, 28);

        jButtonConsultarEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/consultar16.png"))); // NOI18N
        jPanel4.add(jButtonConsultarEstado);
        jButtonConsultarEstado.setBounds(320, 20, 30, 27);

        jPanelCI.add(jPanel4);
        jPanel4.setBounds(10, 130, 860, 60);

        jLabel10.setText("Orgão Emissor:");
        jPanelCI.add(jLabel10);
        jLabel10.setBounds(300, 70, 120, 14);

        jComboBoxOrgaoEmissor.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxOrgaoEmissor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SSP/SP", "SSP/MG" }));
        jComboBoxOrgaoEmissor.setToolTipText("Orgão Responsável por Emitir o Documento\n Exemplo: SSP/SP - Secretaria de Segurança Pública de São Paulo");
        jPanelCI.add(jComboBoxOrgaoEmissor);
        jComboBoxOrgaoEmissor.setBounds(300, 90, 110, 26);

        jButtonAddOrgaoEmissor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanelCI.add(jButtonAddOrgaoEmissor);
        jButtonAddOrgaoEmissor.setBounds(410, 90, 30, 28);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Doc. de Origem:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 12))); // NOI18N
        jPanel5.setLayout(null);

        jTextFieldDocFolha.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanel5.add(jTextFieldDocFolha);
        jTextFieldDocFolha.setBounds(150, 70, 50, 26);

        jLabel13.setText("Folha:");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(150, 50, 30, 14);

        jLabel14.setText("Livro:");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(100, 50, 27, 14);

        jTextFieldDocLivro.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanel5.add(jTextFieldDocLivro);
        jTextFieldDocLivro.setBounds(100, 70, 50, 26);

        jLabel15.setText("Número:");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(200, 50, 70, 14);

        jTextFieldDocNumero.setColumns(32);
        jTextFieldDocNumero.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanel5.add(jTextFieldDocNumero);
        jTextFieldDocNumero.setBounds(200, 70, 300, 26);

        jLabel16.setText("Tipo:");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(10, 50, 60, 14);

        jComboBoxDocTipo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxDocTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CN", "CC" }));
        jComboBoxDocTipo.setToolTipText("Tipo de Documento de Registro: Exemplo:  CN - Certidão de Nascimento / CC - Certidão de Casamento");
        jPanel5.add(jComboBoxDocTipo);
        jComboBoxDocTipo.setBounds(10, 70, 53, 26);

        jButtonAddCertidao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanel5.add(jButtonAddCertidao);
        jButtonAddCertidao.setBounds(70, 70, 30, 28);

        jRadioButtonDocAntigo.setText("Antigo");
        jRadioButtonDocAntigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDocAntigoActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButtonDocAntigo);
        jRadioButtonDocAntigo.setBounds(10, 20, 80, 23);

        jRadioButtonDocNovo.setText("Novo");
        jRadioButtonDocNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDocNovoActionPerformed(evt);
            }
        });
        jPanel5.add(jRadioButtonDocNovo);
        jRadioButtonDocNovo.setBounds(90, 20, 80, 23);

        jLabel18.setText("UF:");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(370, 20, 40, 14);

        jComboBoxDocUF.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanel5.add(jComboBoxDocUF);
        jComboBoxDocUF.setBounds(400, 20, 70, 26);

        jButtonAddDocUF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanel5.add(jButtonAddDocUF);
        jButtonAddDocUF.setBounds(470, 20, 30, 28);

        jLabel19.setText("Cidade:");
        jPanel5.add(jLabel19);
        jLabel19.setBounds(520, 20, 60, 14);

        jComboBoxDocCidade.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanel5.add(jComboBoxDocCidade);
        jComboBoxDocCidade.setBounds(580, 20, 240, 26);

        jButtonAddDocCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanel5.add(jButtonAddDocCidade);
        jButtonAddDocCidade.setBounds(820, 20, 30, 28);

        jLabel20.setText("Comarca:");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(510, 70, 70, 14);

        jComboBox4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanel5.add(jComboBox4);
        jComboBox4.setBounds(580, 70, 240, 26);

        jButtonAddDocComarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanel5.add(jButtonAddDocComarca);
        jButtonAddDocComarca.setBounds(820, 70, 30, 28);

        jButtonConsultarComarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/consultar16.png"))); // NOI18N
        jPanel5.add(jButtonConsultarComarca);
        jButtonConsultarComarca.setBounds(820, 20, 30, 27);

        jPanelCI.add(jPanel5);
        jPanel5.setBounds(10, 190, 860, 130);

        jLabel17.setText("Dt. Exped:");
        jPanelCI.add(jLabel17);
        jLabel17.setBounds(200, 70, 90, 14);

        try {
            jFormattedTextFieldCIDE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCIDE.setToolTipText("Data de Expedição do Documento de Identificação");
        jFormattedTextFieldCIDE.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelCI.add(jFormattedTextFieldCIDE);
        jFormattedTextFieldCIDE.setBounds(200, 90, 100, 26);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filiação:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 12))); // NOI18N
        jPanel1.setLayout(null);

        jLabel21.setText("Pai:");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(10, 30, 40, 14);

        jLabel22.setText("Mãe:");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(10, 80, 50, 14);

        jTextFieldFiliacaoPai.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanel1.add(jTextFieldFiliacaoPai);
        jTextFieldFiliacaoPai.setBounds(10, 50, 420, 26);

        jTextFieldFiliacaoMae.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanel1.add(jTextFieldFiliacaoMae);
        jTextFieldFiliacaoMae.setBounds(10, 100, 420, 26);

        jPanelCI.add(jPanel1);
        jPanel1.setBounds(10, 320, 440, 140);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Obs:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 12))); // NOI18N
        jPanel6.setLayout(null);

        jTextAreaCIObs.setColumns(20);
        jTextAreaCIObs.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTextAreaCIObs.setRows(5);
        jScrollPane1.setViewportView(jTextAreaCIObs);

        jPanel6.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 270, 110);

        jPanelCI.add(jPanel6);
        jPanel6.setBounds(450, 320, 290, 140);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Foto:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 12))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );

        jPanelCI.add(jPanel7);
        jPanel7.setBounds(740, 320, 130, 140);

        jTabbedPane.addTab("Carteira de Identidade:", jPanelCI);

        jPanelCI2.setLayout(null);

        jLabel23.setText("* CPF:");
        jPanelCI2.add(jLabel23);
        jLabel23.setBounds(10, 10, 60, 14);

        try {
            jFormattedTextFieldCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPF.setToolTipText("CPF - Cadastro de Pessoa Física");
        jFormattedTextFieldCPF.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelCI2.add(jFormattedTextFieldCPF);
        jFormattedTextFieldCPF.setBounds(10, 30, 140, 26);

        jLabel24.setText("Dt. Emissão:");
        jPanelCI2.add(jLabel24);
        jLabel24.setBounds(150, 10, 110, 14);

        try {
            jFormattedTextFieldCPFDE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCPFDE.setToolTipText("Data de Emissão do CPF");
        jFormattedTextFieldCPFDE.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelCI2.add(jFormattedTextFieldCPFDE);
        jFormattedTextFieldCPFDE.setBounds(150, 30, 100, 26);
        jPanelCI2.add(jSeparator1);
        jSeparator1.setBounds(10, 70, 860, 2);

        jLabel25.setText("* Título de Eleitor:");
        jPanelCI2.add(jLabel25);
        jLabel25.setBounds(10, 90, 150, 14);

        try {
            jFormattedTextFieldTE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTE.setToolTipText("Título de Eleitor");
        jFormattedTextFieldTE.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelCI2.add(jFormattedTextFieldTE);
        jFormattedTextFieldTE.setBounds(10, 110, 140, 26);

        try {
            jFormattedTextFieldTEDE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTEDE.setToolTipText("Data de Emissão do Título de Eleitor");
        jFormattedTextFieldTEDE.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelCI2.add(jFormattedTextFieldTEDE);
        jFormattedTextFieldTEDE.setBounds(290, 110, 100, 26);

        jComboBoxTEUF.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelCI2.add(jComboBoxTEUF);
        jComboBoxTEUF.setBounds(390, 110, 70, 26);

        jButtonAddUF2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanelCI2.add(jButtonAddUF2);
        jButtonAddUF2.setBounds(460, 110, 30, 28);

        jComboBoxTEMunicipio.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelCI2.add(jComboBoxTEMunicipio);
        jComboBoxTEMunicipio.setBounds(490, 110, 350, 26);

        jButtonAddCidade2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanelCI2.add(jButtonAddCidade2);
        jButtonAddCidade2.setBounds(840, 110, 30, 28);
        jPanelCI2.add(jSeparator2);
        jSeparator2.setBounds(10, 150, 860, 10);

        jLabel26.setText("Dt. Emissão:");
        jPanelCI2.add(jLabel26);
        jLabel26.setBounds(290, 90, 100, 20);

        jLabel27.setText("UF:");
        jPanelCI2.add(jLabel27);
        jLabel27.setBounds(390, 90, 50, 14);

        jLabel28.setText("Município:");
        jPanelCI2.add(jLabel28);
        jLabel28.setBounds(490, 90, 90, 14);

        jLabel29.setText("* PIS/PASEP:");
        jPanelCI2.add(jLabel29);
        jLabel29.setBounds(10, 170, 110, 14);

        jLabel30.setText("Zona:");
        jPanelCI2.add(jLabel30);
        jLabel30.setBounds(150, 90, 60, 14);

        jLabel31.setText("Seção:");
        jPanelCI2.add(jLabel31);
        jLabel31.setBounds(220, 90, 60, 14);

        try {
            jFormattedTextFieldPISPASEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldPISPASEP.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelCI2.add(jFormattedTextFieldPISPASEP);
        jFormattedTextFieldPISPASEP.setBounds(10, 190, 140, 26);

        try {
            jFormattedTextFieldPISPASEPDE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldPISPASEPDE.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelCI2.add(jFormattedTextFieldPISPASEPDE);
        jFormattedTextFieldPISPASEPDE.setBounds(150, 190, 100, 26);

        jLabel32.setText("Dt. Emissão:");
        jPanelCI2.add(jLabel32);
        jLabel32.setBounds(150, 170, 100, 14);
        jPanelCI2.add(jSeparator3);
        jSeparator3.setBounds(10, 230, 860, 10);

        jLabel33.setText("* CNH:");
        jPanelCI2.add(jLabel33);
        jLabel33.setBounds(10, 250, 34, 14);

        try {
            jFormattedTextFieldCNH.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCNH.setToolTipText("CNH - Carteira Nacional de Habilitação");
        jFormattedTextFieldCNH.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelCI2.add(jFormattedTextFieldCNH);
        jFormattedTextFieldCNH.setBounds(10, 270, 140, 26);

        try {
            jFormattedTextFieldCNH1Habilitacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCNH1Habilitacao.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelCI2.add(jFormattedTextFieldCNH1Habilitacao);
        jFormattedTextFieldCNH1Habilitacao.setBounds(360, 270, 100, 26);

        jLabel34.setText("Validade:");
        jPanelCI2.add(jLabel34);
        jLabel34.setBounds(150, 250, 80, 14);

        jComboBoxCNHCategoria.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxCNHCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AB" }));
        jPanelCI2.add(jComboBoxCNHCategoria);
        jComboBoxCNHCategoria.setBounds(250, 270, 80, 26);

        jLabel35.setText("Categoria:");
        jPanelCI2.add(jLabel35);
        jLabel35.setBounds(250, 250, 80, 14);

        jButtonAddCNHCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanelCI2.add(jButtonAddCNHCategoria);
        jButtonAddCNHCategoria.setBounds(330, 270, 30, 28);

        jLabel36.setText("1° Habili.:");
        jPanelCI2.add(jLabel36);
        jLabel36.setBounds(360, 250, 100, 14);

        try {
            jFormattedTextFieldCNHValidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCNHValidade.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelCI2.add(jFormattedTextFieldCNHValidade);
        jFormattedTextFieldCNHValidade.setBounds(150, 270, 100, 26);

        jLabel37.setText("Permissão:");
        jPanelCI2.add(jLabel37);
        jLabel37.setBounds(460, 250, 90, 14);

        jComboBoxCNHPermissao.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxCNHPermissao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NÃO", "SIM" }));
        jPanelCI2.add(jComboBoxCNHPermissao);
        jComboBoxCNHPermissao.setBounds(460, 270, 110, 26);

        jLabel38.setText("Dt. Emissão:");
        jPanelCI2.add(jLabel38);
        jLabel38.setBounds(10, 310, 100, 14);

        try {
            jFormattedTextFieldCNHDE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCNHDE.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelCI2.add(jFormattedTextFieldCNHDE);
        jFormattedTextFieldCNHDE.setBounds(10, 330, 100, 26);

        jTextAreaCNHObs.setColumns(20);
        jTextAreaCNHObs.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTextAreaCNHObs.setRows(5);
        jScrollPane2.setViewportView(jTextAreaCNHObs);

        jPanelCI2.add(jScrollPane2);
        jScrollPane2.setBounds(610, 270, 260, 90);

        jComboBoxCNHUF.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelCI2.add(jComboBoxCNHUF);
        jComboBoxCNHUF.setBounds(270, 330, 70, 26);

        jLabel40.setText("UF:");
        jPanelCI2.add(jLabel40);
        jLabel40.setBounds(270, 310, 50, 14);

        jButtonAddUF3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanelCI2.add(jButtonAddUF3);
        jButtonAddUF3.setBounds(340, 330, 30, 28);

        jButtonAddCNHPermissao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanelCI2.add(jButtonAddCNHPermissao);
        jButtonAddCNHPermissao.setBounds(570, 270, 30, 28);

        jComboBox1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelCI2.add(jComboBox1);
        jComboBox1.setBounds(370, 330, 200, 26);

        jButtonAddCNHCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanelCI2.add(jButtonAddCNHCidade);
        jButtonAddCNHCidade.setBounds(570, 330, 30, 28);

        jLabel41.setText("Cidade:");
        jPanelCI2.add(jLabel41);
        jLabel41.setBounds(370, 310, 70, 14);
        jPanelCI2.add(jSeparator4);
        jSeparator4.setBounds(10, 370, 860, 10);

        jLabel42.setText("Obs:");
        jPanelCI2.add(jLabel42);
        jLabel42.setBounds(610, 250, 23, 14);

        jComboBox2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DETRAN/SP", "DETRAN/MG" }));
        jPanelCI2.add(jComboBox2);
        jComboBox2.setBounds(110, 330, 130, 26);

        jLabel39.setText("Orgão Emissor:");
        jPanelCI2.add(jLabel39);
        jLabel39.setBounds(110, 310, 130, 14);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanelCI2.add(jButton1);
        jButton1.setBounds(240, 330, 30, 28);

        jFormattedTextFieldTEZona.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelCI2.add(jFormattedTextFieldTEZona);
        jFormattedTextFieldTEZona.setBounds(150, 110, 70, 26);

        jFormattedTextFieldTESecao.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelCI2.add(jFormattedTextFieldTESecao);
        jFormattedTextFieldTESecao.setBounds(220, 110, 70, 27);

        jTabbedPane.addTab("Outros Documentos:", jPanelCI2);

        jPanelEndereco.setLayout(null);

        jLabel43.setText("País:");
        jPanelEndereco.add(jLabel43);
        jLabel43.setBounds(10, 10, 50, 14);

        jComboBoxEnderecoPais.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelEndereco.add(jComboBoxEnderecoPais);
        jComboBoxEnderecoPais.setBounds(10, 30, 190, 26);

        jLabel44.setText("UF:");
        jPanelEndereco.add(jLabel44);
        jLabel44.setBounds(230, 10, 50, 14);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanelEndereco.add(jButton2);
        jButton2.setBounds(640, 30, 30, 28);

        jComboBoxEnderecoUF.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelEndereco.add(jComboBoxEnderecoUF);
        jComboBoxEnderecoUF.setBounds(230, 30, 80, 26);

        jLabel45.setText("Cidade:");
        jPanelEndereco.add(jLabel45);
        jLabel45.setBounds(340, 10, 70, 14);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanelEndereco.add(jButton3);
        jButton3.setBounds(840, 90, 30, 28);

        jComboBoxEnderecoCidade.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelEndereco.add(jComboBoxEnderecoCidade);
        jComboBoxEnderecoCidade.setBounds(340, 30, 300, 26);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanelEndereco.add(jButton4);
        jButton4.setBounds(840, 30, 30, 28);

        jComboBoxEnderecoCEP.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelEndereco.add(jComboBoxEnderecoCEP);
        jComboBoxEnderecoCEP.setBounds(670, 30, 170, 26);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanelEndereco.add(jButton5);
        jButton5.setBounds(310, 30, 30, 28);

        jLabel46.setText("Zona:");
        jPanelEndereco.add(jLabel46);
        jLabel46.setBounds(10, 70, 28, 14);

        jComboBoxEnderecoZona.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "URBANA", "RURAL" }));
        jPanelEndereco.add(jComboBoxEnderecoZona);
        jComboBoxEnderecoZona.setBounds(10, 90, 150, 20);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanelEndereco.add(jButton6);
        jButton6.setBounds(200, 30, 30, 28);

        jPanelEndereco.add(jComboBoxEnderecoBairro);
        jComboBoxEnderecoBairro.setBounds(190, 90, 320, 20);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanelEndereco.add(jButton7);
        jButton7.setBounds(160, 90, 30, 28);

        jLabel47.setText("Bairro:");
        jPanelEndereco.add(jLabel47);
        jLabel47.setBounds(190, 70, 32, 14);

        jLabel48.setText("Logradouro:");
        jPanelEndereco.add(jLabel48);
        jLabel48.setBounds(540, 70, 100, 14);

        jComboBoxEnderecoLogradouro.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jPanelEndereco.add(jComboBoxEnderecoLogradouro);
        jComboBoxEnderecoLogradouro.setBounds(540, 90, 300, 26);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanelEndereco.add(jButton8);
        jButton8.setBounds(270, 150, 30, 28);

        jLabel49.setText("N°:");
        jPanelEndereco.add(jLabel49);
        jLabel49.setBounds(10, 130, 40, 14);
        jPanelEndereco.add(jTextFieldEnderecoNumero);
        jTextFieldEnderecoNumero.setBounds(10, 150, 90, 20);

        jLabel50.setText("Tipo do Imóvel:");
        jPanelEndereco.add(jLabel50);
        jLabel50.setBounds(100, 130, 120, 14);

        jComboBoxEnderecoTipo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBoxEnderecoTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "APARTAMENTO", "CASA", "PRÉDIO", "CONDOMÍNIO" }));
        jPanelEndereco.add(jComboBoxEnderecoTipo);
        jComboBoxEnderecoTipo.setBounds(100, 150, 170, 26);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/16x16/add16.png"))); // NOI18N
        jPanelEndereco.add(jButton9);
        jButton9.setBounds(510, 90, 30, 28);

        jLabel51.setText("Complemento:");
        jPanelEndereco.add(jLabel51);
        jLabel51.setBounds(300, 130, 120, 14);
        jPanelEndereco.add(jTextFieldEnderecoComplemento);
        jTextFieldEnderecoComplemento.setBounds(300, 150, 310, 20);

        jTableEndereco.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTableEndereco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Título 5", "Título 6", "Título 7", "Título 8", "Título 9", "Título 10", "Título 11", "Título 12"
            }
        ));
        jTableEndereco.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane3.setViewportView(jTableEndereco);

        jPanelEndereco.add(jScrollPane3);
        jScrollPane3.setBounds(10, 250, 860, 170);

        jTextAreaEnderecoObs.setColumns(20);
        jTextAreaEnderecoObs.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTextAreaEnderecoObs.setRows(5);
        jScrollPane4.setViewportView(jTextAreaEnderecoObs);

        jPanelEndereco.add(jScrollPane4);
        jScrollPane4.setBounds(612, 150, 260, 90);

        jLabel52.setText("Obs:");
        jPanelEndereco.add(jLabel52);
        jLabel52.setBounds(610, 130, 23, 14);

        jLabel53.setText("CEP:");
        jPanelEndereco.add(jLabel53);
        jLabel53.setBounds(670, 10, 23, 14);

        jTabbedPane.addTab("Endereço:", jPanelEndereco);

        jPanelTelefones.setLayout(null);

        jLabel54.setText("Tipo:");
        jPanelTelefones.add(jLabel54);
        jLabel54.setBounds(10, 10, 24, 14);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CELULAR" }));
        jPanelTelefones.add(jComboBox3);
        jComboBox3.setBounds(10, 30, 160, 20);
        jPanelTelefones.add(jButton10);
        jButton10.setBounds(170, 30, 30, 28);

        jLabel55.setText("Operedora:");
        jPanelTelefones.add(jLabel55);
        jLabel55.setBounds(200, 10, 100, 14);

        jComboBox5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VIVO", "TIM", "CLARO", "OI" }));
        jPanelTelefones.add(jComboBox5);
        jComboBox5.setBounds(200, 30, 90, 26);

        jTabbedPane.addTab("Telefones:", jPanelTelefones);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 882, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("eMail:", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 882, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("tab6", jPanel3);

        getContentPane().add(jTabbedPane);
        jTabbedPane.setBounds(0, 70, 890, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGravarAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarAlterarActionPerformed
        // TODO add your handling code here:
        //VerificadorPessoa();
        //jPanelCPF.setEnabled(false);
        teste();
    }//GEN-LAST:event_jButtonGravarAlterarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        Sair();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:
        //jTabbedPane.add(jPanelCPF); 
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jRadioButtonDocAntigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDocAntigoActionPerformed
        // TODO add your handling code here:
        jRadioButtonDocNovo.setSelected(false);
        jTextFieldDocFolha.setEnabled(true);
        jTextFieldDocLivro.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonDocAntigoActionPerformed

    private void jRadioButtonDocNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDocNovoActionPerformed
        // TODO add your handling code here:
        jRadioButtonDocAntigo.setSelected(false);
        jTextFieldDocFolha.setEnabled(false);
        jTextFieldDocLivro.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonDocNovoActionPerformed

    public void Sair(){
        this.dispose();
    }
    
    public void Iniciar(){
        this.setTitle("");
        this.setSize(900, 600);
        jRadioButtonDocAntigo.setSelected(true);
    }
    
    public void teste(){
        if (jTabbedPane.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null,"Campos de Dados em Branco... ","Informação: ",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAddCNHCategoria;
    private javax.swing.JButton jButtonAddCNHCidade;
    private javax.swing.JButton jButtonAddCNHPermissao;
    private javax.swing.JButton jButtonAddCertidao;
    private javax.swing.JButton jButtonAddCidade;
    private javax.swing.JButton jButtonAddCidade2;
    private javax.swing.JButton jButtonAddDocCidade;
    private javax.swing.JButton jButtonAddDocComarca;
    private javax.swing.JButton jButtonAddDocUF;
    private javax.swing.JButton jButtonAddOrgaoEmissor;
    private javax.swing.JButton jButtonAddPais;
    private javax.swing.JButton jButtonAddRG;
    private javax.swing.JButton jButtonAddSexo;
    private javax.swing.JButton jButtonAddUF;
    private javax.swing.JButton jButtonAddUF2;
    private javax.swing.JButton jButtonAddUF3;
    private javax.swing.JButton jButtonConsultarCidade;
    private javax.swing.JButton jButtonConsultarComarca;
    private javax.swing.JButton jButtonConsultarEstado;
    private javax.swing.JButton jButtonGravarAlterar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBoxCNHCategoria;
    private javax.swing.JComboBox jComboBoxCNHPermissao;
    private javax.swing.JComboBox jComboBoxCNHUF;
    private javax.swing.JComboBox jComboBoxDocCidade;
    private javax.swing.JComboBox jComboBoxDocTipo;
    private javax.swing.JComboBox jComboBoxDocUF;
    private javax.swing.JComboBox jComboBoxEnderecoBairro;
    private javax.swing.JComboBox jComboBoxEnderecoCEP;
    private javax.swing.JComboBox jComboBoxEnderecoCidade;
    private javax.swing.JComboBox jComboBoxEnderecoLogradouro;
    private javax.swing.JComboBox jComboBoxEnderecoPais;
    private javax.swing.JComboBox jComboBoxEnderecoTipo;
    private javax.swing.JComboBox jComboBoxEnderecoUF;
    private javax.swing.JComboBox jComboBoxEnderecoZona;
    private javax.swing.JComboBox jComboBoxNaturalidadeCidade;
    private javax.swing.JComboBox jComboBoxNaturalidadePais;
    private javax.swing.JComboBox jComboBoxNaturalidadeUF;
    private javax.swing.JComboBox jComboBoxOrgaoEmissor;
    private javax.swing.JComboBox jComboBoxRGUF;
    private javax.swing.JComboBox jComboBoxSexo;
    private javax.swing.JComboBox jComboBoxTEMunicipio;
    private javax.swing.JComboBox jComboBoxTEUF;
    private javax.swing.JFormattedTextField jFormattedTextFieldCIDE;
    private javax.swing.JFormattedTextField jFormattedTextFieldCNH;
    private javax.swing.JFormattedTextField jFormattedTextFieldCNH1Habilitacao;
    private javax.swing.JFormattedTextField jFormattedTextFieldCNHDE;
    private javax.swing.JFormattedTextField jFormattedTextFieldCNHValidade;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPFDE;
    private javax.swing.JFormattedTextField jFormattedTextFieldDN;
    private javax.swing.JFormattedTextField jFormattedTextFieldPISPASEP;
    private javax.swing.JFormattedTextField jFormattedTextFieldPISPASEPDE;
    private javax.swing.JFormattedTextField jFormattedTextFieldTE;
    private javax.swing.JFormattedTextField jFormattedTextFieldTEDE;
    private javax.swing.JFormattedTextField jFormattedTextFieldTESecao;
    private javax.swing.JFormattedTextField jFormattedTextFieldTEZona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelCI;
    private javax.swing.JPanel jPanelCI2;
    private javax.swing.JPanel jPanelEndereco;
    private javax.swing.JPanel jPanelTelefones;
    private javax.swing.JRadioButton jRadioButtonDocAntigo;
    private javax.swing.JRadioButton jRadioButtonDocNovo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTableEndereco;
    private javax.swing.JTextArea jTextAreaCIObs;
    private javax.swing.JTextArea jTextAreaCNHObs;
    private javax.swing.JTextArea jTextAreaEnderecoObs;
    private javax.swing.JTextField jTextFieldAgnome;
    private javax.swing.JTextField jTextFieldDocFolha;
    private javax.swing.JTextField jTextFieldDocLivro;
    private javax.swing.JTextField jTextFieldDocNumero;
    private javax.swing.JTextField jTextFieldEnderecoComplemento;
    private javax.swing.JTextField jTextFieldEnderecoNumero;
    private javax.swing.JTextField jTextFieldFiliacaoMae;
    private javax.swing.JTextField jTextFieldFiliacaoPai;
    private javax.swing.JTextField jTextFieldNomeCompleto;
    private javax.swing.JTextField jTextFieldPrenome;
    private javax.swing.JTextField jTextFieldRIC;
    private javax.swing.JTextField jTextFieldSobrenome;
    // End of variables declaration//GEN-END:variables
}
