/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package relatorios;

import connect.ConexaoRelatorio;
import base.ctr.BaseCTR;
import java.awt.HeadlessException;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import view.escola.AlunoConsultaDIALOG;

/**
 *
 * @author Douglas Estanislau Pereira
 */
public class RelatorioIndividualdoAlunoRL extends javax.swing.JInternalFrame {

    /**
     * Creates new form RelatorioIndividualdoAlunoRL
     */
    public RelatorioIndividualdoAlunoRL() {
        initComponents();
        Iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGravarAlterar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jComboBoxAlunoUF = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAlunoRA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAlunoNome = new javax.swing.JTextField();

        getContentPane().setLayout(null);

        jButtonGravarAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/48x48/GerarRelatorio48.png"))); // NOI18N
        jButtonGravarAlterar.setToolTipText("Gerar Relatório");
        jButtonGravarAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGravarAlterar);
        jButtonGravarAlterar.setBounds(0, 0, 80, 80);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/png/48x48/Sair48.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(80, 0, 80, 80);

        jComboBoxAlunoUF.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        getContentPane().add(jComboBoxAlunoUF);
        jComboBoxAlunoUF.setBounds(20, 150, 60, 28);

        jLabel4.setText("UF:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 130, 51, 18);

        jLabel5.setText("RA:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 130, 70, 18);

        jTextFieldAlunoRA.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jTextFieldAlunoRA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAlunoRAKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldAlunoRA);
        jTextFieldAlunoRA.setBounds(80, 150, 130, 28);

        jLabel2.setText("Aluno:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 130, 100, 18);

        jTextFieldAlunoNome.setEditable(false);
        jTextFieldAlunoNome.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        getContentPane().add(jTextFieldAlunoNome);
        jTextFieldAlunoNome.setBounds(210, 150, 560, 28);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGravarAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarAlterarActionPerformed
        // TODO add your handling code here:
        //VerificadorPessoa();
        //MododeGravacao();
        relatorio();
    }//GEN-LAST:event_jButtonGravarAlterarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        Sair();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jTextFieldAlunoRAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAlunoRAKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER){
            ConsultarVerificadorAluno();
            //MostrarDadosTabelaRelatoriosAluno();
            jTextFieldAlunoRA.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldAlunoRAKeyPressed

    public void Sair(){
        this.dispose();
    }
    
    public void ConsultarVerificadorAluno(){
        try{
            BaseCTR consultarCTR = new BaseCTR();
            ResultSet rs=null;
            rs=consultarCTR.VerificadorRelatarPessoaAluno(jComboBoxAlunoUF.getSelectedItem().toString(), jTextFieldAlunoRA.getText().toUpperCase().replace(".", "").replace("-", ""));
            int v = 0;
            while(rs.next()){       
                v = (rs.getInt("verificador"));  
            }
            if (v == 0){
                JOptionPane.showMessageDialog(null,"RG/RA não encontrado ou não existente. Verifique...","Informação: ",JOptionPane.INFORMATION_MESSAGE);
                jTextFieldAlunoRA.setText("");
                jTextFieldAlunoNome.setText("");
                jTextFieldAlunoRA.requestFocus();
                
                AlunoConsultaDIALOG  jDialog = new AlunoConsultaDIALOG(null, true);
                jDialog.setModal(true);
                jDialog.setVisible(true);
                jComboBoxAlunoUF.setSelectedItem(jDialog.getGetuf());
                jTextFieldAlunoRA.setText(jDialog.getGetid());
                jTextFieldAlunoNome.setText(jDialog.getGetnome());
            }else{
                ConsultarRelatarAlunoNome();
            }
         }
         catch (HeadlessException | SQLException e){
            System.out.println(e.getMessage());    
         }
    }
    
    public void ConsultarRelatarAlunoNome(){
        try{
            BaseCTR consultar = new BaseCTR();
            ResultSet rs=null;
            rs=consultar.ConsultarRelatarPessoaNome(jComboBoxAlunoUF.getSelectedItem().toString(), jTextFieldAlunoRA.getText().toUpperCase().replace(".", "").replace("-", ""));
            while (rs.next()){
                jTextFieldAlunoNome.setText((rs.getString("pessoa_nome")));
            }
        }
        catch (SQLException e){
            System.out.println(e.getMessage());    
        }
    }
    
    public void ConsultarUF(){
        try{
            BaseCTR consultarCTR = new BaseCTR();
            ResultSet rs=null;
            rs=consultarCTR.ConsultarUF();
            jComboBoxAlunoUF.removeAllItems();
            //jComboBoxProfessorUF.removeAllItems();
            //jComboBoxProfessorUF1.removeAllItems();
            while(rs.next()){       
                jComboBoxAlunoUF.addItem(rs.getString("uf_nome"));    
                //jComboBoxProfessorUF.addItem(rs.getString("uf_nome"));    
                //jComboBoxProfessorUF1.addItem(rs.getString("uf_nome"));    
            }
         }
         catch (SQLException e){
            System.out.println(e.getMessage());    
            }
    }
    
    public void relatorio(){
        try{
            HashMap filtro = new HashMap();
            filtro.put("ra", jTextFieldAlunoRA.getText());
            filtro.put("uf", jComboBoxAlunoUF.getSelectedItem());
            String so = String.valueOf(System.getProperty("os.name"));
            System.out.println(so);
            if(so.equals("Linux")){
                File homedir = new File(System.getProperty("user.home"));
                System.out.println(homedir);
                JasperPrint print = JasperFillManager.fillReport(homedir+"SGU/relatoriodealunos.jasper", filtro, ConexaoRelatorio.getControlaConexao());
                JasperViewer viewer = new JasperViewer(print, false);
                viewer.setVisible(true);
            }else{
                JasperPrint print = JasperFillManager.fillReport("C:/SGU/relatoriodealunos.jasper", filtro, ConexaoRelatorio.getControlaConexao());
                JasperViewer viewer = new JasperViewer(print, false);
                viewer.setVisible(true);
            }
            
            //JasperExportManager.exportReportToPdfFile(print, "/home/administrador/RelatorioClientes.pdf");
            
        }catch (ClassNotFoundException | SQLException | JRException ex){
            System.out.println("Problemas ao Gerar Relatório: "+ex.getMessage());
        }
    }

    public void Iniciar(){
        this.setTitle("Relatório - Individual do Aluno");
        this.setSize(900, 400);
        //jTextFieldAlunoNome.setEnabled(false);
        ConsultarUF();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGravarAlterar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox jComboBoxAlunoUF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldAlunoNome;
    private javax.swing.JTextField jTextFieldAlunoRA;
    // End of variables declaration//GEN-END:variables

    
}
